"""Generate a compact LaTeX roughness-summary table from FV benchmark data.

Example:
  python scripts/make_table_from_sur_roughness.py \
    --per-surface outputs/paper_alicona_benchmark/per_surface.csv \
    --out manuscript/tables/alicona_roughness_median_abs.tex
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np


def _latex_escape(s: str) -> str:
    return s.replace("_", "\\_")


def _pretty_method(m: str) -> str:
    if m == "classical":
        return "Classical"
    if m == "quantum_like":
        return "Quantum-like"
    if m == "hybrid":
        return "Hybrid"
    return _latex_escape(m)


def _method_order(methods: set[str]) -> list[str]:
    preferred = ["classical", "quantum_like", "hybrid"]
    return [m for m in preferred if m in methods] + sorted([m for m in methods if m not in preferred])


def write_table(*, per_surface: Path, out: Path, caption: str, label: str, digits: int, bias_suffix: str) -> None:
    with per_surface.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise SystemExit(f"No rows found in {per_surface}")

    methods = _method_order({str(r["method"]) for r in rows})
    metrics = ["Sa", "Sq", "Sz"]

    out.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("% Auto-generated by scripts/make_table_from_sur_roughness.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\footnotesize")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{label}}}")
    lines.append("\\begin{tabular}{lrrr}")
    lines.append("\\toprule")
    lines.append(
        "Method & Median $|\\Delta S_a|$ (nm) & Median $|\\Delta S_q|$ (nm) & Median $|\\Delta S_z|$ (nm) \\\\"
    )
    lines.append("\\midrule")

    for method in methods:
        vals: list[str] = []
        for metric in metrics:
            bias_key = f"bias_{metric}{bias_suffix}_nm" if bias_suffix else f"bias_{metric}_nm"
            arr = np.array(
                [abs(float(r[bias_key])) for r in rows if str(r["method"]) == method],
                dtype=float,
            )
            vals.append(f"${np.median(arr):.{digits}f}$")
        lines.append(f"{_pretty_method(method)} & " + " & ".join(vals) + " " + "\\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("\\end{table}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate a compact FV roughness-summary LaTeX table")
    ap.add_argument(
        "--per-surface",
        type=Path,
        default=Path("outputs/paper_alicona_benchmark/per_surface.csv"),
        help="Path to per_surface.csv produced by scripts/benchmark_sur_interferometry.py",
    )
    ap.add_argument("--out", type=Path, required=True, help="Output .tex file")
    ap.add_argument("--digits", type=int, default=1)
    ap.add_argument(
        "--bias-suffix",
        type=str,
        default="",
        help="Optional suffix inserted into bias column names, e.g. '_bw' for bias_Sa_bw_nm.",
    )
    ap.add_argument(
        "--caption",
        type=str,
        default="Focus-variation (FV) measured surfaces: median absolute error of reconstructed roughness parameters relative to roughness values computed on the native FV \\texttt{.sur} height maps after masking explicit invalid pixels and removing a best-fit plane.",
    )
    ap.add_argument("--label", type=str, default="tab:alicona_roughness_median_abs")
    args = ap.parse_args()

    write_table(
        per_surface=args.per_surface,
        out=args.out,
        caption=str(args.caption),
        label=str(args.label),
        digits=int(args.digits),
        bias_suffix=str(args.bias_suffix),
    )
    print(f"Wrote: {args.out}")


if __name__ == "__main__":
    main()