#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import hashlib
from pathlib import Path
import shutil
import subprocess
import sys
import tarfile
import textwrap

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from qiprof.labels import decode_sur_stem
from qiprof.metrics import detrend_plane
from qiprof.surfaces import load_surface_sur


ROW_END = "\\\\"


def _run_text(cmd: list[str]) -> str:
    try:
        return subprocess.check_output(cmd, cwd=ROOT, text=True).strip()
    except Exception:
        return "unavailable"


def _load_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _unique_surface_rows(per_surface_csv: Path) -> list[dict[str, str]]:
    rows = _load_csv(per_surface_csv)
    by_stem: dict[str, dict[str, str]] = {}
    for row in rows:
        stem = row["stem"]
        by_stem.setdefault(stem, row)
    return [by_stem[key] for key in sorted(by_stem)]


def _counts(rows: list[dict[str, str]], key: str) -> list[tuple[str, int]]:
    out: dict[str, int] = {}
    for row in rows:
        out[row[key]] = out.get(row[key], 0) + 1
    return sorted(out.items(), key=lambda item: (item[0].lower(), item[1]))


def _write_group_size_table(path: Path, surface_rows: list[dict[str, str]]) -> None:
    materials = _counts(surface_rows, "material")
    treatments = _counts(surface_rows, "treatment")
    nrows = max(len(materials), len(treatments))
    lines = [
        "% Auto-generated by scripts/make_q1_reproducibility_package.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\caption{Measured-surface group sizes used for material- and treatment-level summaries and leave-one-group-out controls. Counts are unique focus-variation \\texttt{.sur} surfaces after collapsing Monte Carlo repetitions and reconstruction methods, not per-method or per-repetition rows.}",
        "\\label{tab:measured_group_sizes}",
        "\\begin{tabularx}{\\textwidth}{XrXr}",
        "\\toprule",
        "Material group & $n$ & Treatment class & $n$ " + ROW_END,
        "\\midrule",
    ]
    for idx in range(nrows):
        material, material_n = materials[idx] if idx < len(materials) else ("", "")
        treatment, treatment_n = treatments[idx] if idx < len(treatments) else ("", "")
        lines.append(f"{material} & {material_n} & {treatment} & {treatment_n} {ROW_END}")
    lines.extend([
        "\\bottomrule",
        "\\end{tabularx}",
        "\\end{table}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_detector_parameter_table(path: Path) -> None:
    lines = [
        "% Auto-generated by scripts/make_q1_reproducibility_package.py",
        "\\begin{table*}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{3pt}",
        "\\caption{Parameter audit for the proxy, detector, non-ideality, and roughness-filter controls. The simple measured-surface benchmark uses a cosine--Poisson coincidence proxy under matched detected-count assumptions; rate-model rows identify where accidentals, efficiency imbalance, and nonparalyzable deadtime enter. These settings define the simulation hierarchy and should not be read as a calibrated hardware transfer function.}",
        "\\label{tab:detector_proxy_parameter_audit}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{p{0.20\\textwidth}p{0.20\\textwidth}p{0.22\\textwidth}p{0.21\\textwidth}p{0.12\\textwidth}}",
        "\\toprule",
        "Control / location & Observable model & Count and wavelength settings & Non-idealities or filters & Repetitions " + ROW_END,
        "\\midrule",
        "Measured-surface benchmark & Classical PSI plus direct and hybrid coincidence-proxy branches & $\\lambda_\\mathrm{class}=532$~nm; $\\lambda_1/\\lambda_2=810/809$~nm; difference branch $\\Lambda=655.29~\\mu$m; classical budget $8\\times10^4$ photons/pixel; proxy budget $3\\times10^4$ pairs/pixel & Simple cosine--Poisson proxy; phase steps $0,\\pi/2,\\pi,3\\pi/2$; no imposed stepping jitter or frame drift; hybrid smoothing $\\sigma=1.5$ px & $4$ per surface/method " + ROW_END,
        "Full-dataset rate-model control, ideal & Rate-based coincidence model with matched mean coincidence counts & Gate time $1$~ms; target mean coincidence counts $3\\times10^4$ per pixel; same wavelength settings as the measured benchmark & Accidentals disabled ($\\tau_c=0$); $\\eta_1=\\eta_2=1$; dark rates $0$; deadtime disabled & $4$ per surface/method " + ROW_END,
        "Full-dataset rate-model control, non-ideal & Rate-based coincidence model with matched mean coincidence counts & Gate time $1$~ms; target mean coincidence counts $3\\times10^4$ per pixel; same wavelength settings as the measured benchmark & Accidentals window $\\tau_c=20$~ns; $\\eta_1=0.70$, $\\eta_2=0.50$; dark rates $0$; nonparalyzable deadtime $5$~ns in both arms & $4$ per surface/method " + ROW_END,
        "Measured-surface phase/drift control & Same simple proxy as the measured benchmark & Same count and wavelength settings as the measured benchmark & Phase-jitter branch uses Gaussian phase-step perturbation $\\sigma_\\delta=3^\\circ$; drift branches use $5\\%$ frame-to-frame background and amplitude drift; drift+norm additionally uses least-squares phase recovery with frame-mean normalisation & $4$ per surface/method " + ROW_END,
        "Step-free detector sensitivity & Rate-model control in the representative $S_q\\approx80$~nm step-free regime & $128\\times128$ grid; target mean coincidence counts $3\\times10^4$ per pixel; gate time $1$~ms & Accidentals window $20$~ns; imbalance $\\eta_1=0.70$, $\\eta_2=0.50$; nonparalyzable deadtime $5$~ns; zero-step case isolates direct-branch sensitivity & $10$ per scenario " + ROW_END,
        "Approximate roughness-filter control & Same benchmark-grid reconstructions, roughness descriptors recomputed after Gaussian nesting-index surrogate & Same measured-surface benchmark settings & Approximate Gaussian $S/L$ control on the benchmark grid with $\\lambda_s=2.5~\\mu$m and $\\lambda_c=80.0~\\mu$m & $4$ per surface/method " + ROW_END,
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table*}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_reproducibility_readme(path: Path, *, release_tag: str) -> None:
    python_version = sys.version.replace("\n", " ")
    requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8").strip()
    text = f"""# Quantum_interference reproducibility companion

Release tag: `{release_tag}`
Repository: `https://github.com/dawidkucharski/Quantum_interference`

The release tag is the authoritative pointer to the exact Git commit and public companion package.

This companion package is intentionally derived-data only. It does not include the full native Mountains/DigitalSurf `.sur` files because those raw exports are too large for normal Git history and remain available from the corresponding author on reasonable request. Instead, it provides the benchmark-grid surfaces and CSV artefacts needed to audit the manuscript-facing simulation benchmark.

## Contents

- `benchmark_grid_surfaces_256.npz`: area-averaged, detrended 256 x 256 benchmark-grid surfaces used as interferometric simulation inputs, stored in nm as `height_nm`; accompanying arrays include `valid_mask`, `x_um`, `y_um`, `stem`, `material`, and `treatment`.
- `benchmark_grid_manifest.csv`: one row per downsampled benchmark surface with group labels, lateral sampling, field of view, valid-pixel fraction, and height range.
- `derived_csv/`: public CSV outputs copied from `outputs/paper_alicona_benchmark/`, including per-surface benchmark rows and control summaries.
- `manuscript_tables/`: generated manuscript table sources used by the paper.
- `support_docs/`: public experimental-validation protocol.
- `CITATION.cff`: citation metadata for the public repository and companion package.
- `commands.txt`: exact full-regeneration and smoke-test commands.
- `environment.txt`: Python interpreter and package requirements used for this package.

## Full Regeneration Command

```bash
python scripts/run_paper_measured_benchmark.py
python scripts/run_paper_optprops.py
cd manuscript && latexmk -pdf -bibtex -interaction=nonstopmode main.tex
```

## Fast Smoke Regeneration Command

```bash
python scripts/run_paper_measured_benchmark.py --skip-benchmark --skip-resolution-sensitivity --skip-unwrap-control --skip-rate-model-control --skip-classical-frontier --skip-surface-metadata
cd manuscript && latexmk -pdf -bibtex -interaction=nonstopmode main.tex
```

## Determinism Notes

The measured-surface benchmark uses stable CRC32-derived seeds per surface, method branch, and Monte Carlo repetition. The canonical measured benchmark uses four repetitions per surface and method. The bootstrap confidence intervals use a fixed NumPy generator seed inside `scripts/make_benchmark_stat_tables.py`.

## Python Environment

`{python_version}`

Requirements:

```text
{requirements}
```
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(text).strip() + "\n", encoding="utf-8")


def _write_commands(path: Path) -> None:
    lines = [
        "# Full measured-surface regeneration",
        "python scripts/run_paper_measured_benchmark.py",
        "",
        "# Full optical-property controls",
        "python scripts/run_paper_optprops.py",
        "",
        "# Fast paper-facing smoke regeneration using existing benchmark CSVs",
        "python scripts/run_paper_measured_benchmark.py --skip-benchmark --skip-resolution-sensitivity --skip-unwrap-control --skip-rate-model-control --skip-classical-frontier --skip-surface-metadata",
        "",
        "# Manuscript build",
        "cd manuscript && latexmk -pdf -bibtex -interaction=nonstopmode main.tex",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _write_environment(path: Path) -> None:
    version = sys.version.replace("\n", " ")
    requirements = (ROOT / "requirements.txt").read_text(encoding="utf-8")
    text = f"Python: {version}\n\nrequirements.txt:\n{requirements}"
    path.write_text(text, encoding="utf-8")


def _export_benchmark_grid_surfaces(asset_dir: Path, *, nx: int, ny: int) -> None:
    data_dir = ROOT / "data"
    paths = sorted(data_dir.glob("*.sur"))
    if not paths:
        raise FileNotFoundError("No data/*.sur files found for benchmark-grid export")

    heights: list[np.ndarray] = []
    masks: list[np.ndarray] = []
    xs: list[np.ndarray] = []
    ys: list[np.ndarray] = []
    stems: list[str] = []
    materials: list[str] = []
    treatments: list[str] = []
    manifest: list[dict[str, object]] = []

    for path in paths:
        surface = load_surface_sur(path, target_nx=nx, target_ny=ny, resample="area")
        valid_mask = getattr(surface, "valid_mask", None)
        h_true = detrend_plane(surface.h, valid_mask=valid_mask)
        if valid_mask is None:
            mask = np.isfinite(h_true)
        else:
            mask = valid_mask & np.isfinite(h_true)
        if np.any(mask):
            fill = float(np.nanmedian(h_true[mask]))
            h_true = np.where(mask, h_true, fill)
        else:
            h_true = np.nan_to_num(h_true, nan=0.0)
        label = decode_sur_stem(path.stem)
        x_um = np.asarray(surface.x, dtype=float) * 1e6
        y_um = np.asarray(surface.y, dtype=float) * 1e6
        height_nm = np.asarray(h_true, dtype=np.float32) * 1e9
        heights.append(height_nm)
        masks.append(np.asarray(mask, dtype=bool))
        xs.append(x_um.astype(np.float32))
        ys.append(y_um.astype(np.float32))
        stems.append(path.stem)
        materials.append(label.material_en)
        treatments.append(label.treatment_en)
        dx_um = float(np.mean(np.diff(x_um))) if x_um.size > 1 else 0.0
        dy_um = float(np.mean(np.diff(y_um))) if y_um.size > 1 else 0.0
        manifest.append(
            {
                "stem": path.stem,
                "material": label.material_en,
                "treatment": label.treatment_en,
                "nx": int(nx),
                "ny": int(ny),
                "dx_um": f"{dx_um:.6f}",
                "dy_um": f"{dy_um:.6f}",
                "x_span_mm": f"{((float(x_um[-1]) - float(x_um[0])) / 1000.0) if x_um.size > 1 else 0.0:.6f}",
                "y_span_mm": f"{((float(y_um[-1]) - float(y_um[0])) / 1000.0) if y_um.size > 1 else 0.0:.6f}",
                "valid_fraction": f"{float(np.mean(mask)):.6f}",
                "height_min_nm": f"{float(np.min(height_nm)):.6f}",
                "height_max_nm": f"{float(np.max(height_nm)):.6f}",
            }
        )

    np.savez_compressed(
        asset_dir / "benchmark_grid_surfaces_256.npz",
        height_nm=np.stack(heights, axis=0),
        valid_mask=np.stack(masks, axis=0),
        x_um=np.stack(xs, axis=0),
        y_um=np.stack(ys, axis=0),
        stem=np.array(stems),
        material=np.array(materials),
        treatment=np.array(treatments),
    )
    _write_csv(
        asset_dir / "benchmark_grid_manifest.csv",
        manifest,
        [
            "stem",
            "material",
            "treatment",
            "nx",
            "ny",
            "dx_um",
            "dy_um",
            "x_span_mm",
            "y_span_mm",
            "valid_fraction",
            "height_min_nm",
            "height_max_nm",
        ],
    )


def _copy_public_outputs(asset_dir: Path) -> None:
    csv_root = asset_dir / "derived_csv"
    output_root = ROOT / "outputs" / "paper_alicona_benchmark"
    for csv_path in sorted(output_root.rglob("*.csv")):
        rel = csv_path.relative_to(ROOT)
        dest = csv_root / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(csv_path, dest)

    table_root = asset_dir / "manuscript_tables"
    table_root.mkdir(parents=True, exist_ok=True)
    for table_path in sorted((ROOT / "manuscript" / "tables").glob("*.tex")):
        shutil.copy2(table_path, table_root / table_path.name)

    docs_root = asset_dir / "support_docs"
    docs_root.mkdir(parents=True, exist_ok=True)
    for doc_name in ["experimental_validation_protocol.md"]:
        source = ROOT / "docs" / doc_name
        if source.exists():
            shutil.copy2(source, docs_root / doc_name)

    citation = ROOT / "CITATION.cff"
    if citation.exists():
        shutil.copy2(citation, asset_dir / citation.name)


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _make_tarball(source_dir: Path, tar_path: Path) -> str:
    tar_path.parent.mkdir(parents=True, exist_ok=True)
    if tar_path.exists():
        tar_path.unlink()
    with tarfile.open(tar_path, "w:gz") as archive:
        archive.add(source_dir, arcname=source_dir.name)
    checksum = _sha256(tar_path)
    (tar_path.with_suffix(tar_path.suffix + ".sha256")).write_text(f"{checksum}  {tar_path.name}\n", encoding="utf-8")
    return checksum


def main() -> None:
    parser = argparse.ArgumentParser(description="Create reproducibility tables and release companion asset")
    parser.add_argument("--release-tag", default="submission-2026-04-28-q1")
    parser.add_argument("--nx", type=int, default=256)
    parser.add_argument("--ny", type=int, default=256)
    args = parser.parse_args()

    per_surface_csv = ROOT / "outputs" / "paper_alicona_benchmark" / "per_surface.csv"
    surface_rows = _unique_surface_rows(per_surface_csv)

    _write_group_size_table(ROOT / "manuscript" / "tables" / "measured_group_sizes.tex", surface_rows)
    _write_detector_parameter_table(ROOT / "manuscript" / "tables" / "detector_proxy_parameter_audit.tex")

    archive_root = ROOT / "outputs" / "submission_archive"
    asset_dir = archive_root / "q1_reproducibility_companion"
    if asset_dir.exists():
        shutil.rmtree(asset_dir)
    asset_dir.mkdir(parents=True, exist_ok=True)

    readme_path = asset_dir / "README.md"
    _write_reproducibility_readme(
        readme_path,
        release_tag=str(args.release_tag),
    )
    docs_readme = ROOT / "docs" / "reproducibility_companion.md"
    docs_readme.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(readme_path, docs_readme)
    _write_commands(asset_dir / "commands.txt")
    _write_environment(asset_dir / "environment.txt")
    _export_benchmark_grid_surfaces(asset_dir, nx=int(args.nx), ny=int(args.ny))
    _copy_public_outputs(asset_dir)

    tar_path = archive_root / f"quantum_interference_reproducibility_{args.release_tag}.tar.gz"
    checksum = _make_tarball(asset_dir, tar_path)
    print(f"Wrote: {ROOT / 'manuscript' / 'tables' / 'measured_group_sizes.tex'}")
    print(f"Wrote: {ROOT / 'manuscript' / 'tables' / 'detector_proxy_parameter_audit.tex'}")
    print(f"Wrote: {docs_readme}")
    print(f"Wrote: {tar_path}")
    print(f"SHA256: {checksum}")


if __name__ == "__main__":
    main()