"""Generate LaTeX tables from plot_sweep summary.csv.

This is intended for manuscript-ready (booktabs) tables.

Example:
  python scripts/make_table_from_summary.py \
    --summary outputs/figures_paper_optprops/summary.csv \
    --out manuscript/tables/optprops_rmse_step0.tex \
    --metric rmse_h_nm \
    --step-nm 0
"""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass(frozen=True)
class SummaryRow:
    method: str
    step_nm: float
    rms_nm: float
    sample_reflectivity: float
    sample_visibility_scale: float
    coherence_model: str
    incidence_cos: float
    n: int
    rmse_mean: float
    rmse_std: float
    bias_Sa_mean: float
    bias_Sa_std: float
    bias_Sq_mean: float
    bias_Sq_std: float
    bias_Sz_mean: float
    bias_Sz_std: float
    step_err_mean: float
    step_err_std: float


def _f(x: str) -> float:
    return float(x.strip())


def _i(x: str) -> int:
    return int(float(x.strip()))


def _get(d: dict[str, str], key: str, default: str = "") -> str:
    return d[key] if key in d and d[key] not in (None, "") else default


def read_summary(path: Path) -> list[SummaryRow]:
    rows: list[SummaryRow] = []
    with open(path, "r", encoding="utf-8") as f:
        r = csv.DictReader(f)
        for d in r:
            rows.append(
                SummaryRow(
                    method=str(d["method"]),
                    step_nm=_f(d["step_nm"]),
                    rms_nm=_f(d["rms_nm"]),
                    sample_reflectivity=_f(_get(d, "sample_reflectivity", "1")),
                    sample_visibility_scale=_f(_get(d, "sample_visibility_scale", "1")),
                    coherence_model=_get(d, "coherence_model", "none"),
                    incidence_cos=_f(_get(d, "incidence_cos", "1")),
                    n=_i(d["n"]),
                    rmse_mean=_f(d["rmse_h_nm_mean"]),
                    rmse_std=_f(d["rmse_h_nm_std"]),
                    bias_Sa_mean=_f(d["bias_Sa_nm_mean"]),
                    bias_Sa_std=_f(d["bias_Sa_nm_std"]),
                    bias_Sq_mean=_f(d["bias_Sq_nm_mean"]),
                    bias_Sq_std=_f(d["bias_Sq_nm_std"]),
                    bias_Sz_mean=_f(d["bias_Sz_nm_mean"]),
                    bias_Sz_std=_f(d["bias_Sz_nm_std"]),
                    step_err_mean=_f(d["step_err_nm_mean"]),
                    step_err_std=_f(d["step_err_nm_std"]),
                )
            )
    return rows


def _fmt_num(x: float, *, digits: int) -> str:
    return f"{x:.{digits}f}"


def _latex_escape(s: str) -> str:
    return s.replace("_", "\\_")


def _default_method_order(methods: Iterable[str]) -> list[str]:
    # Prefer a consistent, manuscript-friendly order.
    order = [
        "classical",
        "quant_diff",
        "quant_sum",
        "quant_noon2",
        "quant_su11",
        "hybrid_diff",
        "hybrid_sum",
        "hybrid_noon2",
        "hybrid_su11",
    ]
    methods_set = set(methods)
    out = [m for m in order if m in methods_set]
    out += sorted([m for m in methods_set if m not in set(out)])
    return out


def _pretty_method(m: str) -> str:
    if m == "classical":
        return "Classical"
    if m.startswith("quant_"):
        return "Q-" + m.split("_", 1)[1]
    if m.startswith("hybrid_"):
        return "H-" + m.split("_", 1)[1]
    return _latex_escape(m)


def write_rmse_table(
    *,
    rows: list[SummaryRow],
    out: Path,
    step_nm: float,
    methods: list[str] | None,
    caption: str,
    label: str,
    digits: int,
) -> None:
    # Filter to fixed step height.
    filtered = [r for r in rows if abs(r.step_nm - float(step_nm)) < 1e-9]
    if not filtered:
        raise SystemExit(f"No rows found for step_nm={step_nm} in summary")

    # Scenario key excludes method.
    def sk(r: SummaryRow) -> tuple[float, float, float, str, float]:
        return (r.rms_nm, r.sample_reflectivity, r.sample_visibility_scale, r.coherence_model, r.incidence_cos)

    scenarios = sorted({sk(r) for r in filtered})
    all_methods = sorted({r.method for r in filtered})
    method_cols = methods if methods is not None and len(methods) > 0 else _default_method_order(all_methods)

    # Index for lookup.
    lookup: dict[tuple[tuple[float, float, float, str, float], str], SummaryRow] = {}
    for r in filtered:
        lookup[(sk(r), r.method)] = r

    out.parent.mkdir(parents=True, exist_ok=True)

    # For each method, use two numeric columns (mean, std) with an inter-column
    # ± token, so all ± symbols align vertically across the table.
    pm_token = r"\,\ensuremath{\pm}\,"
    colspec = "rrrr" + (f"r@{{{pm_token}}}r" * len(method_cols))

    lines: list[str] = []
    lines.append("% Auto-generated by scripts/make_table_from_summary.py")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\footnotesize")
    lines.append("\\setlength{\\tabcolsep}{2.4pt}")
    lines.append(f"\\caption{{{caption}}}")
    lines.append(f"\\label{{{label}}}")
    lines.append("\\resizebox{\\textwidth}{!}{%")
    lines.append(f"\\begin{{tabular}}{{{colspec}}}")
    lines.append("\\toprule")

    header = [
        "RMS (nm)",
        "$R$",
        "$V_\\mathrm{scale}$",
        "Model",
    ] + [f"\\multicolumn{{2}}{{c}}{{{_pretty_method(m)}}}" for m in method_cols]
    lines.append(" & ".join(header) + " \\\\")
    lines.append("\\midrule")

    for (rms_nm, refl, vis, coh_model, inc_cos) in scenarios:
        row = [
            f"{rms_nm:.0f}",
            f"{refl:.2f}",
            f"{vis:.2f}",
            _latex_escape(coh_model),
        ]

        for m in method_cols:
            rr = lookup.get(((rms_nm, refl, vis, coh_model, inc_cos), m))
            if rr is None:
                row.extend(["--", "--"])
            else:
                row.extend(
                    [
                        f"${_fmt_num(rr.rmse_mean, digits=digits)}$",
                        f"${_fmt_num(rr.rmse_std, digits=digits)}$",
                    ]
                )

        lines.append(" & ".join(row) + " \\\\")

    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    lines.append("}%")
    lines.append("\\end{table}")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Create LaTeX tables from plot_sweep summary.csv")
    ap.add_argument("--summary", type=str, required=True, help="Path to summary.csv")
    ap.add_argument("--out", type=str, required=True, help="Output .tex file")
    ap.add_argument("--step-nm", type=float, default=0.0, help="Step height to filter (nm)")
    ap.add_argument(
        "--methods",
        type=str,
        default="",
        help="Comma-separated method list (e.g. classical,quant_diff,quant_noon2,hybrid_diff,hybrid_noon2).",
    )
    ap.add_argument("--digits", type=int, default=1, help="Decimal digits for mean/std")
    ap.add_argument(
        "--caption",
        type=str,
        default="Height RMSE (detrended) for step-free surfaces (mean $\\pm$ std over repeats).",
    )
    ap.add_argument("--label", type=str, default="tab:optprops_rmse")

    args = ap.parse_args()

    summary = Path(args.summary)
    out = Path(args.out)

    rows = read_summary(summary)
    methods = [m.strip() for m in str(args.methods).split(",") if m.strip()] if args.methods else None

    write_rmse_table(
        rows=rows,
        out=out,
        step_nm=float(args.step_nm),
        methods=methods,
        caption=str(args.caption),
        label=str(args.label),
        digits=int(args.digits),
    )

    print(f"Wrote: {out}")


if __name__ == "__main__":
    main()
