#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(_ROOT / "src"))

from qiprof.plot_style import apply_publication_style


METHODS = [
    ("classical", "Classical", "#1f77b4"),
    ("quant_noon2", "Q-noon2", "#d62728"),
    ("hybrid_noon2", "H-noon2", "#2ca02c"),
]

ROW_END = "\\\\"


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def _close(a: float, b: float, *, tol: float = 1e-9) -> bool:
    return abs(a - b) <= tol


def _extract_values(
    rows: list[dict[str, str]],
    *,
    sample_reflectivity: float,
    sample_visibility_scale: float,
    rms_nm: float,
) -> dict[str, tuple[float, float]]:
    out: dict[str, tuple[float, float]] = {}
    for method, _, _ in METHODS:
        match = None
        for row in rows:
            if row.get("method") != method:
                continue
            if not _close(float(row["sample_reflectivity"]), sample_reflectivity):
                continue
            if not _close(float(row["sample_visibility_scale"]), sample_visibility_scale):
                continue
            if not _close(float(row["rms_nm"]), rms_nm):
                continue
            match = row
            break
        if match is None:
            raise ValueError(
                f"Could not find scenario row for method={method}, R={sample_reflectivity}, "
                f"Vscale={sample_visibility_scale}, rms={rms_nm} in summary CSV"
            )
        out[method] = (float(match["rmse_h_nm_mean"]), float(match["rmse_h_nm_std"]))
    return out


def _write_table(
    out_path: Path,
    *,
    scenario_values: list[tuple[str, dict[str, tuple[float, float]]]],
    label: str,
    gate_time_ms: float,
    tau_c_ns: float,
    eta1: float,
    eta2: float,
    deadtime_ns: float,
) -> None:
    lines = [
        "% Auto-generated by scripts/make_detector_sensitivity_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{5pt}",
        (
            "\\caption{Representative detector-model sensitivity check for the step-free transition regime at "
            "$R=1.00$, $V_\\mathrm{scale}=1.00$, and true roughness $S_q=80$~nm. The rate-based rows match the "
            f"mean coincidence counts of the simple proxy using a {gate_time_ms:.1f}~ms gate. Accidentals use "
            f"a {tau_c_ns:.1f}~ns coincidence window; the imbalance scenario additionally uses $\\eta_1={eta1:.2f}$ "
            f"and $\\eta_2={eta2:.2f}$; the deadtime scenario uses a nonparalyzable {deadtime_ns:.1f}~ns detector proxy. "
            "Entries are height RMSE mean $\\pm$ std over 10 repeats.}"
        ),
        f"\\label{{{label}}}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Scenario & Classical & Q-noon2 & H-noon2 " + ROW_END,
        "\\midrule",
    ]
    for scenario_label, values in scenario_values:
        row = [scenario_label]
        for method, _, _ in METHODS:
            mean, std = values[method]
            row.append(f"${mean:.2f} \\pm {std:.2f}$")
        lines.append(" & ".join(row) + " " + ROW_END)
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _plot(
    out_path: Path,
    *,
    scenario_short_labels: list[str],
    scenario_values: list[tuple[str, dict[str, tuple[float, float]]]],
    title: str,
) -> None:
    apply_publication_style(base_fontsize=8.5)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    x = np.arange(len(scenario_values), dtype=float)
    fig, ax = plt.subplots(1, 1, figsize=(4.8, 2.8), constrained_layout=True)
    for method, label, color in METHODS:
        means = np.array([values[method][0] for _, values in scenario_values], dtype=float)
        stds = np.array([values[method][1] for _, values in scenario_values], dtype=float)
        ax.errorbar(
            x,
            means,
            yerr=stds,
            marker="o",
            markersize=4.0,
            linewidth=1.3,
            capsize=2.8,
            color=color,
            label=label,
        )
    ax.set_xticks(x, scenario_short_labels, rotation=18, ha="right")
    ax.set_yscale("log")
    ax.set_ylabel("Height RMSE (nm) [log]")
    ax.set_title(title)
    ax.grid(True, which="both", axis="y", alpha=0.25)
    ax.legend(frameon=False, fontsize=7.2)
    fig.savefig(out_path)
    plt.close(fig)


def main() -> int:
    ap = argparse.ArgumentParser(description="Create detector-sensitivity figure and LaTeX table from summary CSVs")
    ap.add_argument("--baseline-summary", type=Path, required=True)
    ap.add_argument("--rate-summary", type=Path, required=True)
    ap.add_argument("--accidentals-summary", type=Path, required=True)
    ap.add_argument("--imbalance-summary", type=Path, required=True)
    ap.add_argument("--deadtime-summary", type=Path, required=True)
    ap.add_argument("--out-table", type=Path, default=Path("manuscript/tables/optprops_detector_sensitivity.tex"))
    ap.add_argument("--out-figure", type=Path, default=Path("outputs/paper_optprops_detector_sensitivity/detector_sensitivity_summary.pdf"))
    ap.add_argument("--sample-reflectivity", type=float, default=1.0)
    ap.add_argument("--sample-visibility-scale", type=float, default=1.0)
    ap.add_argument("--rms-nm", type=float, default=80.0)
    ap.add_argument("--label", type=str, default="tab:optprops_detector_sensitivity")
    ap.add_argument("--gate-time-ms", type=float, default=1.0)
    ap.add_argument("--tau-c-ns", type=float, default=20.0)
    ap.add_argument("--eta1", type=float, default=0.70)
    ap.add_argument("--eta2", type=float, default=0.50)
    ap.add_argument("--deadtime-ns", type=float, default=5.0)
    args = ap.parse_args()

    scenario_specs = [
        ("Simple coincidence proxy", "Simple", _load_rows(args.baseline_summary)),
        ("Rate model, matched mean counts", "Rate", _load_rows(args.rate_summary)),
        ("Rate + accidentals", "+acc.", _load_rows(args.accidentals_summary)),
        (
            f"Rate + accidentals + $\\eta$ imbalance ({args.eta1:.2f}/{args.eta2:.2f})",
            "+imb.",
            _load_rows(args.imbalance_summary),
        ),
        ("Rate + accidentals + deadtime", "+deadtime", _load_rows(args.deadtime_summary)),
    ]

    scenario_values: list[tuple[str, dict[str, tuple[float, float]]]] = []
    scenario_short_labels: list[str] = []
    for long_label, short_label, rows in scenario_specs:
        values = _extract_values(
            rows,
            sample_reflectivity=float(args.sample_reflectivity),
            sample_visibility_scale=float(args.sample_visibility_scale),
            rms_nm=float(args.rms_nm),
        )
        scenario_values.append((long_label, values))
        scenario_short_labels.append(short_label)

    _write_table(
        args.out_table,
        scenario_values=scenario_values,
        label=str(args.label),
        gate_time_ms=float(args.gate_time_ms),
        tau_c_ns=float(args.tau_c_ns),
        eta1=float(args.eta1),
        eta2=float(args.eta2),
        deadtime_ns=float(args.deadtime_ns),
    )
    _plot(
        args.out_figure,
        scenario_short_labels=scenario_short_labels,
        scenario_values=scenario_values,
        title="Detector-model sensitivity ($S_q=80$ nm, $R=1.0$, $V_\\mathrm{scale}=1.0$)",
    )
    print(f"Wrote: {args.out_table}")
    print(f"Wrote: {args.out_figure}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())