#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
import sys

sys.path.insert(0, str(_ROOT / "src"))

from qiprof.plot_style import apply_publication_style


METHODS = [
    ("classical", "Classical", "#1f77b4"),
    ("quant_noon2", "Q-noon2", "#d62728"),
    ("hybrid_noon2", "H-noon2", "#2ca02c"),
]

ROW_END = "\\\\"


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def _close(a: float, b: float, *, tol: float = 1e-9) -> bool:
    return abs(a - b) <= tol


def _extract_values(
    rows: list[dict[str, str]],
    *,
    sample_reflectivity: float,
    sample_visibility_scale: float,
    rms_nm: float,
) -> dict[str, tuple[float, float]]:
    out: dict[str, tuple[float, float]] = {}
    for method, _, _ in METHODS:
        match = None
        for row in rows:
            if row.get("method") != method:
                continue
            if not _close(float(row["sample_reflectivity"]), sample_reflectivity):
                continue
            if not _close(float(row["sample_visibility_scale"]), sample_visibility_scale):
                continue
            if not _close(float(row["rms_nm"]), rms_nm):
                continue
            match = row
            break
        if match is None:
            raise ValueError(
                f"Could not find scenario row for method={method}, R={sample_reflectivity}, "
                f"Vscale={sample_visibility_scale}, rms={rms_nm} in summary CSV"
            )
        out[method] = (float(match["rmse_h_nm_mean"]), float(match["rmse_h_nm_std"]))
    return out


def _write_table(
    out_path: Path,
    *,
    scenario_values: list[tuple[str, dict[str, tuple[float, float]]]],
    label: str,
) -> None:
    lines = [
        "% Auto-generated by scripts/make_nonideal_stress_artifacts.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\caption{Representative non-ideality stress test for the step-free optical-property sweep at $R=1.00$, $V_\\mathrm{scale}=1.00$, and true roughness $S_q=80$~nm. Entries are height RMSE mean $\\pm$ std over 10 repeats. The first three rows use the baseline PSI4 reconstruction; the final row is a mitigation control using LSQ reconstruction with frame-mean normalisation under the same $5\\%$ drift.}",
        f"\\label{{{label}}}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Scenario & Classical & Q-noon2 & H-noon2 " + ROW_END,
        "\\midrule",
    ]
    for scenario_label, values in scenario_values:
        row = [scenario_label]
        for method, _, _ in METHODS:
            mean, std = values[method]
            row.append(f"${mean:.2f} \\pm {std:.2f}$")
        lines.append(" & ".join(row) + " " + ROW_END)
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
        "",
    ])
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def _plot(
    out_path: Path,
    *,
    scenario_short_labels: list[str],
    scenario_values: list[tuple[str, dict[str, tuple[float, float]]]],
    title: str,
) -> None:
    apply_publication_style(base_fontsize=8.5)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    x = np.arange(len(scenario_values), dtype=float)
    fig, ax = plt.subplots(1, 1, figsize=(4.2, 2.7), constrained_layout=True)
    for method, label, color in METHODS:
        means = np.array([values[method][0] for _, values in scenario_values], dtype=float)
        stds = np.array([values[method][1] for _, values in scenario_values], dtype=float)
        ax.errorbar(
            x,
            means,
            yerr=stds,
            marker="o",
            markersize=4.0,
            linewidth=1.3,
            capsize=2.8,
            color=color,
            label=label,
        )
    ax.set_xticks(x, scenario_short_labels, rotation=18, ha="right")
    ax.set_yscale("log")
    ax.set_ylabel("Height RMSE (nm) [log]")
    ax.set_title(title)
    ax.grid(True, which="both", axis="y", alpha=0.25)
    ax.legend(frameon=False, fontsize=7.2)
    fig.savefig(out_path)
    plt.close(fig)


def main() -> int:
    ap = argparse.ArgumentParser(description="Create representative robustness figure and LaTeX table from summary CSVs")
    ap.add_argument("--baseline-summary", type=Path, required=True)
    ap.add_argument("--phase-summary", type=Path, required=True)
    ap.add_argument("--drift-summary", type=Path, required=True)
    ap.add_argument("--drift-norm-summary", type=Path, required=True)
    ap.add_argument("--out-table", type=Path, default=Path("manuscript/tables/optprops_nonideal_stress.tex"))
    ap.add_argument("--out-figure", type=Path, default=Path("outputs/paper_optprops_nonideal_stress/nonideal_stress_summary.pdf"))
    ap.add_argument("--sample-reflectivity", type=float, default=1.0)
    ap.add_argument("--sample-visibility-scale", type=float, default=1.0)
    ap.add_argument("--rms-nm", type=float, default=80.0)
    ap.add_argument("--label", type=str, default="tab:optprops_nonideal_stress")
    args = ap.parse_args()

    scenario_specs = [
        ("Baseline", "Base", _load_rows(args.baseline_summary)),
        ("$+3^\\circ$ phase-step jitter", "+3$^\\circ$ jitter", _load_rows(args.phase_summary)),
        ("$+5\\%$ background and amplitude drift", "+5% drift", _load_rows(args.drift_summary)),
        ("Drift + LSQ + frame normalisation", "Drift + norm", _load_rows(args.drift_norm_summary)),
    ]

    scenario_values: list[tuple[str, dict[str, tuple[float, float]]]] = []
    scenario_short_labels: list[str] = []
    for long_label, short_label, rows in scenario_specs:
        values = _extract_values(
            rows,
            sample_reflectivity=float(args.sample_reflectivity),
            sample_visibility_scale=float(args.sample_visibility_scale),
            rms_nm=float(args.rms_nm),
        )
        scenario_values.append((long_label, values))
        scenario_short_labels.append(short_label)

    _write_table(args.out_table, scenario_values=scenario_values, label=str(args.label))
    _plot(
        args.out_figure,
        scenario_short_labels=scenario_short_labels,
        scenario_values=scenario_values,
        title="Representative non-ideality stress test ($S_q=80$ nm, $R=1.0$, $V_\\mathrm{scale}=1.0$)",
    )
    print(f"Wrote: {args.out_table}")
    print(f"Wrote: {args.out_figure}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())