#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
import subprocess
import sys

import numpy as np


_ROOT = Path(__file__).resolve().parents[1]


SCENARIOS = [
    {
        "key": "baseline",
        "label": "Baseline",
    },
    {
        "key": "phase_jitter",
        "label": "$+3^\\circ$ jitter",
    },
    {
        "key": "drift",
        "label": "$+5\\%$ drift",
    },
    {
        "key": "drift_norm",
        "label": "Drift + norm",
    },
]

METHOD_ORDER = ["classical", "quantum_like", "hybrid"]
METHOD_LABEL = {
    "classical": "C",
    "quantum_like": "Q",
    "hybrid": "H",
}

METRICS = [
    ("height_rmse_nm", "Height RMSE (nm)"),
    ("abs_bias_Sa_bw_nm", "$|\\Delta S_a|$ (nm)"),
    ("abs_bias_Sq_bw_nm", "$|\\Delta S_q|$ (nm)"),
    ("abs_bias_Sz_bw_nm", "$|\\Delta S_z|$ (nm)"),
]


def _run(cmd: list[str]) -> None:
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def _expand_inputs(root: Path, patterns: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[Path] = set()
    for pattern in patterns:
        candidate = (root / pattern).resolve()
        if candidate.exists():
            if candidate not in seen:
                out.append(str(candidate))
                seen.add(candidate)
            continue
        matches = sorted(root.glob(pattern))
        for match in matches:
            resolved = match.resolve()
            if resolved not in seen:
                out.append(str(resolved))
                seen.add(resolved)
    if not out:
        raise FileNotFoundError(f"No input surfaces matched: {patterns}")
    return out


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def _collapse_surface_rows(rows: list[dict[str, str]]) -> list[dict[str, float | str]]:
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["stem"], row["method"])].append(row)

    out: list[dict[str, float | str]] = []
    for (stem, method), entries in sorted(grouped.items()):
        out.append(
            {
                "stem": stem,
                "method": method,
                "height_rmse_nm": float(np.median([float(e["height_rmse_nm"]) for e in entries])),
                "abs_bias_Sa_bw_nm": float(np.median([abs(float(e["bias_Sa_bw_nm"])) for e in entries])),
                "abs_bias_Sq_bw_nm": float(np.median([abs(float(e["bias_Sq_bw_nm"])) for e in entries])),
                "abs_bias_Sz_bw_nm": float(np.median([abs(float(e["bias_Sz_bw_nm"])) for e in entries])),
            }
        )
    return out


def _summary_by_method(rows: list[dict[str, float | str]]) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}
    for method in {str(row["method"]) for row in rows}:
        method_rows = [row for row in rows if str(row["method"]) == method]
        out[method] = {
            "height_rmse_nm": float(np.median([float(row["height_rmse_nm"]) for row in method_rows])),
            "abs_bias_Sa_bw_nm": float(np.median([float(row["abs_bias_Sa_bw_nm"]) for row in method_rows])),
            "abs_bias_Sq_bw_nm": float(np.median([float(row["abs_bias_Sq_bw_nm"]) for row in method_rows])),
            "abs_bias_Sz_bw_nm": float(np.median([float(row["abs_bias_Sz_bw_nm"]) for row in method_rows])),
        }
    return out


def _write_summary_csv(path: Path, summaries: dict[str, dict[str, dict[str, float]]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "scenario",
        "method",
        "height_rmse_nm",
        "abs_bias_Sa_bw_nm",
        "abs_bias_Sq_bw_nm",
        "abs_bias_Sz_bw_nm",
    ]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for scenario in SCENARIOS:
            key = str(scenario["key"])
            for method, vals in summaries[key].items():
                writer.writerow({"scenario": key, "method": method, **vals})


def _fmt(value: float) -> str:
    return f"${value:.1f}$"


def _write_latex_table(
    path: Path,
    *,
    label: str,
    summaries: dict[str, dict[str, dict[str, float]]],
    phase_step_sigma_deg: float,
    drift_frac: float,
) -> None:
    row_end = "\\\\"
    lines = [
        "% Auto-generated by scripts/run_paper_measured_nonideal_control.py",
        "\\begin{table*}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        (
            "\\caption{Measured-surface non-ideality control over the full benchmark dataset. "
            "The baseline reuses the canonical measured-surface benchmark; the second and third scenario rerun the same $n=59$ surface dataset with Gaussian phase-step jitter and frame-to-frame background/amplitude drift, respectively; the final scenario keeps the same drift but switches to least-squares phase reconstruction with frame-mean normalisation. "
            f"The non-ideal settings use $\\sigma_\\delta={phase_step_sigma_deg:.1f}^\\circ$ and multiplicative drift of {100.0 * drift_frac:.1f}\\% in both background and fringe amplitude. "
            "Entries report surface-level medians after collapsing repeated runs within each surface and method; roughness endpoints use the matched-bandwidth benchmark-grid reference.}"
        ),
        f"\\label{{{label}}}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lcccccccccccc}",
        "\\toprule",
        "& \\multicolumn{3}{c}{Baseline} & \\multicolumn{3}{c}{$+3^\\circ$ jitter} & \\multicolumn{3}{c}{$+5\\%$ drift} & \\multicolumn{3}{c}{Drift + norm} " + row_end,
        "Endpoint & C & Q & H & C & Q & H & C & Q & H & C & Q & H " + row_end,
        "\\midrule",
    ]
    for metric, metric_label in METRICS:
        row = [metric_label]
        for scenario in SCENARIOS:
            key = str(scenario["key"])
            for method in METHOD_ORDER:
                row.append(_fmt(summaries[key][method][metric]))
        lines.append(" & ".join(row) + " " + row_end)
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table*}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Measured-surface non-ideality control for the paper benchmark")
    ap.add_argument("inputs", nargs="*", default=["data/*.sur"], help="SUR files or glob patterns under the repo root")
    ap.add_argument("--tag", type=str, default="paper_alicona_benchmark")
    ap.add_argument("--nx", type=int, default=256)
    ap.add_argument("--ny", type=int, default=256)
    ap.add_argument("--nreps", type=int, default=4)
    ap.add_argument("--jobs", type=int, default=0)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--skip-benchmark", action="store_true")
    ap.add_argument("--label", type=str, default="tab:benchmark_nonideal_control")
    ap.add_argument("--out-table", type=Path, default=Path("manuscript/tables/benchmark_nonideal_control.tex"))
    ap.add_argument("--phase-step-sigma-deg", type=float, default=3.0)
    ap.add_argument("--drift-frac", type=float, default=0.05)
    args = ap.parse_args()

    root = _ROOT
    py = sys.executable
    out_base = root / "outputs" / str(args.tag)
    control_base = out_base / "nonideal_control"
    expanded_inputs = _expand_inputs(root, list(args.inputs))

    baseline_per_surface = out_base / "per_surface.csv"
    if not baseline_per_surface.exists() and not args.skip_benchmark:
        baseline_cmd = [
            py,
            str(root / "scripts" / "benchmark_sur_interferometry.py"),
            *expanded_inputs,
            "--outdir",
            str(out_base),
            "--nx",
            str(int(args.nx)),
            "--ny",
            str(int(args.ny)),
            "--nreps",
            str(int(args.nreps)),
            "--jobs",
            str(int(args.jobs)),
        ]
        if int(args.limit) > 0:
            baseline_cmd.extend(["--limit", str(int(args.limit))])
        _run(baseline_cmd)

    common_args = [
        py,
        str(root / "scripts" / "benchmark_sur_interferometry.py"),
        *expanded_inputs,
        "--nx",
        str(int(args.nx)),
        "--ny",
        str(int(args.ny)),
        "--nreps",
        str(int(args.nreps)),
        "--jobs",
        str(int(args.jobs)),
    ]

    phase_dir = control_base / "phase_jitter"
    drift_dir = control_base / "drift"
    drift_norm_dir = control_base / "drift_norm"

    if not args.skip_benchmark:
        phase_cmd = [
            *common_args,
            "--outdir",
            str(phase_dir),
            "--phase-step-sigma-deg",
            str(float(args.phase_step_sigma_deg)),
        ]
        drift_cmd = [
            *common_args,
            "--outdir",
            str(drift_dir),
            "--background-drift-frac",
            str(float(args.drift_frac)),
            "--amplitude-drift-frac",
            str(float(args.drift_frac)),
        ]
        drift_norm_cmd = [
            *common_args,
            "--outdir",
            str(drift_norm_dir),
            "--background-drift-frac",
            str(float(args.drift_frac)),
            "--amplitude-drift-frac",
            str(float(args.drift_frac)),
            "--recon",
            "lsq",
            "--normalize-frames",
        ]
        if int(args.limit) > 0:
            phase_cmd.extend(["--limit", str(int(args.limit))])
            drift_cmd.extend(["--limit", str(int(args.limit))])
            drift_norm_cmd.extend(["--limit", str(int(args.limit))])
        _run(phase_cmd)
        _run(drift_cmd)
        _run(drift_norm_cmd)

    summaries = {
        "baseline": _summary_by_method(_collapse_surface_rows(_load_rows(baseline_per_surface))),
        "phase_jitter": _summary_by_method(_collapse_surface_rows(_load_rows(phase_dir / "per_surface.csv"))),
        "drift": _summary_by_method(_collapse_surface_rows(_load_rows(drift_dir / "per_surface.csv"))),
        "drift_norm": _summary_by_method(_collapse_surface_rows(_load_rows(drift_norm_dir / "per_surface.csv"))),
    }

    summary_csv = control_base / "summary.csv"
    _write_summary_csv(summary_csv, summaries)
    _write_latex_table(
        root / args.out_table,
        label=str(args.label),
        summaries=summaries,
        phase_step_sigma_deg=float(args.phase_step_sigma_deg),
        drift_frac=float(args.drift_frac),
    )
    print(f"Wrote: {summary_csv}")
    print(f"Wrote: {root / args.out_table}")


if __name__ == "__main__":
    main()