#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
import sys
from typing import Dict, List, Optional, Tuple

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from qiprof.labels import decode_sur_stem
from qiprof.metrics import detrend_plane, roughness_errors, roughness_metrics
from qiprof.reconstruct import (
    height_from_phase,
    normalize_frames_mean,
    reconstruct_phase_lsq,
    reconstruct_psi4,
    unwrap_phase_2d,
    unwrap_height_with_coarse,
)
from qiprof.sim_classical import simulate_psi4
from qiprof.sim_quantum import effective_wavelength, simulate_coincidence_psi4
from qiprof.surfaces import load_surface_sur


METHOD_ORDER = ["classical", "classical_two_color", "quantum_like", "hybrid_two_color", "hybrid"]
METHOD_LABEL = {
    "classical": "Classical",
    "classical_two_color": "Classical 2-colour",
    "quantum_like": "Q-diff",
    "hybrid_two_color": "H-2-colour",
    "hybrid": "H-diff",
}
ROW_END = r"\\"

TABLE_ROWS = [
    ("height_rmse_nm", "Height RMSE (nm)"),
    ("abs_bias_Sa_bw_nm", r"$|\Delta S_a|$ (nm)"),
    ("abs_bias_Sq_bw_nm", r"$|\Delta S_q|$ (nm)"),
    ("abs_bias_Sz_bw_nm", r"$|\Delta S_z|$ (nm)"),
]


def _rmse_nm(a_m: np.ndarray, b_m: np.ndarray, *, valid_mask: Optional[np.ndarray]) -> float:
    a = detrend_plane(a_m, valid_mask=valid_mask)
    b = detrend_plane(b_m, valid_mask=valid_mask)
    if valid_mask is None:
        mask = np.isfinite(a) & np.isfinite(b)
    else:
        mask = valid_mask & np.isfinite(a) & np.isfinite(b)
    return float(np.sqrt(np.mean(((a - b)[mask]) ** 2)) * 1e9)


def _wrap_to_pi(values: np.ndarray) -> np.ndarray:
    return (values + np.pi) % (2.0 * np.pi) - np.pi


def _decode_label(stem: str) -> Dict[str, str]:
    label = decode_sur_stem(stem)
    return {
        "sample_group": label.sample_group,
        "material_code": label.material_code,
        "treatment_code": label.treatment_code,
        "material": label.material_en,
        "treatment": label.treatment_en,
    }


def _iter_inputs(patterns: List[str]) -> List[Path]:
    paths: List[Path] = []
    for pattern in patterns:
        p = Path(pattern)
        if p.exists():
            paths.append(p)
        else:
            paths.extend(sorted(Path().glob(pattern)))

    seen: set[Path] = set()
    out: List[Path] = []
    for p in paths:
        rp = p.resolve()
        if rp not in seen:
            out.append(p)
            seen.add(rp)
    return out


def _write_csv(path: Path, rows: List[Dict[str, object]]) -> None:
    fieldnames = sorted({key for row in rows for key in row.keys()})
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _phase_from_frames(
    frames: np.ndarray,
    *,
    recon: str,
    normalize_frames: bool,
    unwrap_method: str,
    phase_steps: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    if recon == "lsq":
        frames_used = normalize_frames_mean(frames) if normalize_frames else frames
        phi_w = reconstruct_phase_lsq(frames_used, phase_steps_rad=phase_steps)
    else:
        phi_w = reconstruct_psi4(frames)
    phi_u = unwrap_phase_2d(phi_w, method=unwrap_method)
    return phi_w, phi_u


def _collapse_surface_rows(rows: List[Dict[str, object]]) -> Dict[str, Dict[str, float]]:
    grouped: Dict[Tuple[str, str], List[Dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[(str(row["stem"]), str(row["method"]))].append(row)

    metrics = [metric for metric, _ in TABLE_ROWS]
    summary: Dict[str, Dict[str, float]] = {method: {} for method in METHOD_ORDER}
    for method in METHOD_ORDER:
        per_surface: Dict[str, List[float]] = {metric: [] for metric in metrics}
        for (stem, row_method), entries in grouped.items():
            if row_method != method:
                continue
            for metric in metrics:
                vals = np.array([float(entry[metric]) for entry in entries], dtype=float)
                per_surface[metric].append(float(np.median(vals)))
        if any(per_surface.values()):
            summary[method] = {
                metric: float(np.median(values)) if values else float("nan")
                for metric, values in per_surface.items()
            }
    return summary


def _write_table(path: Path, summary: Dict[str, Dict[str, float]], *, n_surfaces: int) -> None:
    lines = [
        "% Auto-generated by scripts/run_paper_classical_two_color_control.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{Auxiliary full-dataset control separating generic synthetic-wavelength behaviour from the coincidence-model branch over $n={int(n_surfaces)}$ measured surfaces. The classical two-colour control uses two classical PSI stacks at 810 and 809~nm with the total classical photon budget split evenly between wavelengths. Reported values are medians of surface-level medians; roughness biases are referenced to the matched-bandwidth benchmark grid after area-averaged downsampling.}}",
        "\\label{tab:classical_two_color_control}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        f"Endpoint & Classical & Classical 2-colour & Q-diff & H-2-colour & H-diff {ROW_END}",
        "\\midrule",
    ]
    for metric, label in TABLE_ROWS:
        row = [label]
        for method in METHOD_ORDER:
            row.append(f"${summary[method][metric]:.1f}$")
        lines.append(" & ".join(row) + f" {ROW_END}")
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table}",
        "",
    ])
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Measured-surface classical two-colour control for the paper benchmark"
    )
    ap.add_argument("inputs", nargs="*", default=["data/*.sur"], help="SUR files or glob patterns")
    ap.add_argument("--outdir", type=Path, default=Path("outputs/paper_alicona_benchmark/classical_control"))
    ap.add_argument(
        "--table-out",
        type=Path,
        default=Path("manuscript/tables/classical_two_color_control.tex"),
    )
    ap.add_argument("--nx", type=int, default=256)
    ap.add_argument("--ny", type=int, default=256)
    ap.add_argument("--nreps", type=int, default=1)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--recon", type=str, choices=["psi4", "lsq"], default="psi4")
    ap.add_argument("--normalize-frames", action="store_true")
    ap.add_argument("--unwrap-method", type=str, choices=["simple", "least_squares"], default="simple")
    ap.add_argument("--sur-resample", type=str, choices=["area", "index"], default="area")
    ap.add_argument("--lambda-class-nm", type=float, default=532.0)
    ap.add_argument("--class-photons", type=float, default=8e4)
    ap.add_argument("--class-visibility", type=float, default=0.85)
    ap.add_argument("--lambda1-nm", type=float, default=810.0)
    ap.add_argument("--lambda2-nm", type=float, default=809.0)
    ap.add_argument("--quant-pairs", type=float, default=3e4)
    ap.add_argument("--quant-detector-model", type=str, choices=["simple", "rates"], default="simple")
    ap.add_argument("--quant-target-mean-counts", type=float, default=0.0)
    ap.add_argument("--gate-time-s", type=float, default=1.0)
    ap.add_argument("--pair-rate-hz", type=float, default=0.0)
    ap.add_argument("--eta1", type=float, default=1.0)
    ap.add_argument("--eta2", type=float, default=1.0)
    ap.add_argument("--dark1-hz", type=float, default=0.0)
    ap.add_argument("--dark2-hz", type=float, default=0.0)
    ap.add_argument("--tau-c-s", type=float, default=1e-6)
    ap.add_argument("--deadtime1-s", type=float, default=0.0)
    ap.add_argument("--deadtime2-s", type=float, default=0.0)
    ap.add_argument("--hybrid-smooth-sigma-px", type=float, default=1.5)
    args = ap.parse_args()

    paths = _iter_inputs(list(args.inputs))
    if int(args.limit) > 0:
        paths = paths[: int(args.limit)]
    if not paths:
        raise FileNotFoundError("No SUR files matched the requested inputs")

    lam_class = float(args.lambda_class_nm) * 1e-9
    lam1 = float(args.lambda1_nm) * 1e-9
    lam2 = float(args.lambda2_nm) * 1e-9
    lam_eff = effective_wavelength(interferometer="diff", lambda1_m=lam1, lambda2_m=lam2)
    phase_steps = np.array([0.0, 0.5 * np.pi, np.pi, 1.5 * np.pi], dtype=float)

    rows: List[Dict[str, object]] = []
    for p in paths:
        stem = p.stem
        decoded = _decode_label(stem)
        surface = load_surface_sur(
            p,
            target_nx=int(args.nx),
            target_ny=int(args.ny),
            resample=str(args.sur_resample),
        )
        valid_mask = getattr(surface, "valid_mask", None)
        h_true = detrend_plane(surface.h, valid_mask=valid_mask)
        if valid_mask is not None and bool(np.any(valid_mask)):
            fill = float(np.nanmedian(h_true[valid_mask]))
            h_true = np.where(valid_mask, h_true, fill)
        true_m_bw = roughness_metrics(surface.h, valid_mask=valid_mask)

        for rep in range(int(args.nreps)):
            seed_base = (hash(stem) + 1009 * rep) & 0xFFFFFFFF

            I4 = simulate_psi4(
                h_true,
                wavelength_m=lam_class,
                photons_per_pixel=float(args.class_photons),
                visibility=float(args.class_visibility),
                seed=seed_base,
            )
            phi_w_short, phi_u_short = _phase_from_frames(
                I4,
                recon=str(args.recon),
                normalize_frames=bool(args.normalize_frames),
                unwrap_method=str(args.unwrap_method),
                phase_steps=phase_steps,
            )
            h_class = height_from_phase(phi_u_short, wavelength_m=lam_class)

            two_color_photons = 0.5 * float(args.class_photons)
            I4_l1 = simulate_psi4(
                h_true,
                wavelength_m=lam1,
                photons_per_pixel=two_color_photons,
                visibility=float(args.class_visibility),
                seed=(seed_base + 101) & 0xFFFFFFFF,
            )
            I4_l2 = simulate_psi4(
                h_true,
                wavelength_m=lam2,
                photons_per_pixel=two_color_photons,
                visibility=float(args.class_visibility),
                seed=(seed_base + 202) & 0xFFFFFFFF,
            )
            phi1_w, _ = _phase_from_frames(
                I4_l1,
                recon=str(args.recon),
                normalize_frames=bool(args.normalize_frames),
                unwrap_method=str(args.unwrap_method),
                phase_steps=phase_steps,
            )
            phi2_w, _ = _phase_from_frames(
                I4_l2,
                recon=str(args.recon),
                normalize_frames=bool(args.normalize_frames),
                unwrap_method=str(args.unwrap_method),
                phase_steps=phase_steps,
                )
            phi_two_color_w = _wrap_to_pi(phi1_w - phi2_w)
            phi_two_color_u = unwrap_phase_2d(phi_two_color_w, method=str(args.unwrap_method))
            h_two_color = height_from_phase(phi_two_color_u, wavelength_m=lam_eff)

            pair_rate_hz = None
            if str(args.quant_detector_model) == "rates":
                pair_rate_hz = (
                    float(args.pair_rate_hz)
                    if float(args.pair_rate_hz) > 0
                    else float(args.quant_pairs) / float(args.gate_time_s)
                )
            C4 = simulate_coincidence_psi4(
                h_true,
                lambda1_m=lam1,
                lambda2_m=lam2,
                visibility=0.6,
                background=1.0,
                amplitude=1.0,
                pairs_per_pixel=float(args.quant_pairs),
                interferometer="diff",
                detector_model=str(args.quant_detector_model),
                gate_time_s=float(args.gate_time_s),
                pair_rate_hz=pair_rate_hz,
                eta1=float(args.eta1),
                eta2=float(args.eta2),
                dark1_hz=float(args.dark1_hz),
                dark2_hz=float(args.dark2_hz),
                tau_c_s=float(args.tau_c_s),
                deadtime1_s=float(args.deadtime1_s),
                deadtime2_s=float(args.deadtime2_s),
                target_mean_counts_per_pixel=(
                    float(args.quant_target_mean_counts) if float(args.quant_target_mean_counts) > 0 else None
                ),
                seed=(seed_base + 303) & 0xFFFFFFFF,
            )
            _, phi_quant_u = _phase_from_frames(
                C4,
                recon=str(args.recon),
                normalize_frames=bool(args.normalize_frames),
                unwrap_method=str(args.unwrap_method),
                phase_steps=phase_steps,
            )
            h_quant = height_from_phase(phi_quant_u, wavelength_m=lam_eff)

            h_hybrid_two_color = unwrap_height_with_coarse(
                phi_w_short,
                coarse_height_m=h_two_color,
                wavelength_short_m=lam_class,
                coarse_smooth_sigma_px=float(args.hybrid_smooth_sigma_px),
            )
            h_hybrid_quant = unwrap_height_with_coarse(
                phi_w_short,
                coarse_height_m=h_quant,
                wavelength_short_m=lam_class,
                coarse_smooth_sigma_px=float(args.hybrid_smooth_sigma_px),
            )

            methods = {
                "classical": h_class,
                "classical_two_color": h_two_color,
                "quantum_like": h_quant,
                "hybrid_two_color": h_hybrid_two_color,
                "hybrid": h_hybrid_quant,
            }

            for method, h_est in methods.items():
                m_est = roughness_metrics(h_est, valid_mask=valid_mask)
                errs_bw = roughness_errors(m_est, true_m_bw)
                rows.append(
                    {
                        "file": str(p.as_posix()),
                        "stem": stem,
                        **decoded,
                        "rep": int(rep),
                        "method": method,
                        "sur_resample": str(args.sur_resample),
                        "unwrap_method": str(args.unwrap_method),
                        "nx": int(surface.x.size),
                        "ny": int(surface.y.size),
                        "lambda_class_nm": float(args.lambda_class_nm),
                        "lambda1_nm": float(args.lambda1_nm),
                        "lambda2_nm": float(args.lambda2_nm),
                        "lambda_eff_nm": float(lam_eff * 1e9),
                        "Sa_true_bw_nm": float(true_m_bw.Sa * 1e9),
                        "Sq_true_bw_nm": float(true_m_bw.Sq * 1e9),
                        "Sz_true_bw_nm": float(true_m_bw.Sz * 1e9),
                        "Sa_est_nm": float(m_est.Sa * 1e9),
                        "Sq_est_nm": float(m_est.Sq * 1e9),
                        "Sz_est_nm": float(m_est.Sz * 1e9),
                        "bias_Sa_bw_nm": float(errs_bw["bias_Sa"] * 1e9),
                        "bias_Sq_bw_nm": float(errs_bw["bias_Sq"] * 1e9),
                        "bias_Sz_bw_nm": float(errs_bw["bias_Sz"] * 1e9),
                        "abs_bias_Sa_bw_nm": float(abs(errs_bw["bias_Sa"]) * 1e9),
                        "abs_bias_Sq_bw_nm": float(abs(errs_bw["bias_Sq"]) * 1e9),
                        "abs_bias_Sz_bw_nm": float(abs(errs_bw["bias_Sz"]) * 1e9),
                        "height_rmse_nm": _rmse_nm(h_est, h_true, valid_mask=valid_mask),
                    }
                )

    args.outdir.mkdir(parents=True, exist_ok=True)
    args.table_out.parent.mkdir(parents=True, exist_ok=True)
    per_surface = args.outdir / "per_surface.csv"
    _write_csv(per_surface, rows)
    summary = _collapse_surface_rows(rows)
    _write_table(args.table_out, summary, n_surfaces=len(paths))
    print(f"Wrote: {per_surface}")
    print(f"Wrote: {args.table_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())