#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
import subprocess
import sys

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]


SCENARIOS = [
    {
        "key": "simple",
        "label": "Simple proxy",
    },
    {
        "key": "rates",
        "label": "Rate model, matched counts",
    },
    {
        "key": "rates_nonideal",
        "label": "Rate model + accidentals + imbalance + deadtime",
    },
]


def _run(cmd: list[str]) -> None:
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def _expand_inputs(root: Path, patterns: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[Path] = set()
    for pattern in patterns:
        candidate = (root / pattern).resolve()
        if candidate.exists():
            if candidate not in seen:
                out.append(str(candidate))
                seen.add(candidate)
            continue
        matches = sorted(root.glob(pattern))
        for match in matches:
            resolved = match.resolve()
            if resolved not in seen:
                out.append(str(resolved))
                seen.add(resolved)
    if not out:
        raise FileNotFoundError(f"No input surfaces matched: {patterns}")
    return out


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def _collapse_surface_rows(rows: list[dict[str, str]]) -> list[dict[str, float | str]]:
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["stem"], row["method"])].append(row)

    out: list[dict[str, float | str]] = []
    for (stem, method), entries in sorted(grouped.items()):
        out.append(
            {
                "stem": stem,
                "method": method,
                "height_rmse_nm": float(np.median([float(e["height_rmse_nm"]) for e in entries])),
                "abs_bias_Sa_nm": float(np.median([abs(float(e["bias_Sa_nm"])) for e in entries])),
                "abs_bias_Sq_nm": float(np.median([abs(float(e["bias_Sq_nm"])) for e in entries])),
                "abs_bias_Sz_nm": float(np.median([abs(float(e["bias_Sz_nm"])) for e in entries])),
            }
        )
    return out


def _summary_by_method(rows: list[dict[str, float | str]]) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}
    for method in {str(row["method"]) for row in rows}:
        method_rows = [row for row in rows if str(row["method"]) == method]
        out[method] = {
            "height_rmse_nm": float(np.median([float(row["height_rmse_nm"]) for row in method_rows])),
            "abs_bias_Sa_nm": float(np.median([float(row["abs_bias_Sa_nm"]) for row in method_rows])),
            "abs_bias_Sq_nm": float(np.median([float(row["abs_bias_Sq_nm"]) for row in method_rows])),
            "abs_bias_Sz_nm": float(np.median([float(row["abs_bias_Sz_nm"]) for row in method_rows])),
        }
    return out


def _write_summary_csv(path: Path, summaries: dict[str, dict[str, dict[str, float]]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["scenario", "method", "height_rmse_nm", "abs_bias_Sa_nm", "abs_bias_Sq_nm", "abs_bias_Sz_nm"]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for scenario in SCENARIOS:
            key = str(scenario["key"])
            for method, vals in summaries[key].items():
                writer.writerow({"scenario": key, "method": method, **vals})


def _fmt(value: float) -> str:
    return f"${value:.1f}$"


def _write_latex_table(
    path: Path,
    *,
    label: str,
    summaries: dict[str, dict[str, dict[str, float]]],
    gate_time_ms: float,
    tau_c_ns: float,
    eta1: float,
    eta2: float,
    deadtime_ns: float,
) -> None:
    simple = summaries["simple"]
    rates = summaries["rates"]
    nonideal = summaries["rates_nonideal"]
    row_end = "\\\\"
    lines = [
        "% Auto-generated by scripts/run_paper_measured_rate_control.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        (
            "\\caption{Measured-surface rate-model control over the full benchmark dataset. "
            "The canonical simple coincidence proxy is compared against a matched-count rate model and a non-ideal rate model with accidentals, detector-efficiency imbalance, and nonparalyzable deadtime. "
            f"The rate-model controls use a gate time of {gate_time_ms:.3f}~ms; the non-ideal setting additionally uses $\\tau_c={tau_c_ns:.1f}$~ns, "
            f"$\\eta_1={eta1:.2f}$, $\\eta_2={eta2:.2f}$, and deadtime $\\tau_d={deadtime_ns:.1f}$~ns in each arm. "
            "Entries report surface-level medians after collapsing repeated runs within each surface and method.}"
        ),
        f"\\label{{{label}}}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lccccccc}",
        "\\toprule",
        "Endpoint & Classical & Q-like (simple) & Q-like (rates) & Q-like (non-ideal rates) & Hybrid (simple) & Hybrid (rates) & Hybrid (non-ideal rates) " + row_end,
        "\\midrule",
        (
            f"Height RMSE (nm) & {_fmt(simple['classical']['height_rmse_nm'])} & {_fmt(simple['quantum_like']['height_rmse_nm'])} & {_fmt(rates['quantum_like']['height_rmse_nm'])} & {_fmt(nonideal['quantum_like']['height_rmse_nm'])} & {_fmt(simple['hybrid']['height_rmse_nm'])} & {_fmt(rates['hybrid']['height_rmse_nm'])} & {_fmt(nonideal['hybrid']['height_rmse_nm'])} " + row_end
        ),
        (
            f"$|\\Delta S_a|$ (nm) & {_fmt(simple['classical']['abs_bias_Sa_nm'])} & {_fmt(simple['quantum_like']['abs_bias_Sa_nm'])} & {_fmt(rates['quantum_like']['abs_bias_Sa_nm'])} & {_fmt(nonideal['quantum_like']['abs_bias_Sa_nm'])} & {_fmt(simple['hybrid']['abs_bias_Sa_nm'])} & {_fmt(rates['hybrid']['abs_bias_Sa_nm'])} & {_fmt(nonideal['hybrid']['abs_bias_Sa_nm'])} " + row_end
        ),
        (
            f"$|\\Delta S_q|$ (nm) & {_fmt(simple['classical']['abs_bias_Sq_nm'])} & {_fmt(simple['quantum_like']['abs_bias_Sq_nm'])} & {_fmt(rates['quantum_like']['abs_bias_Sq_nm'])} & {_fmt(nonideal['quantum_like']['abs_bias_Sq_nm'])} & {_fmt(simple['hybrid']['abs_bias_Sq_nm'])} & {_fmt(rates['hybrid']['abs_bias_Sq_nm'])} & {_fmt(nonideal['hybrid']['abs_bias_Sq_nm'])} " + row_end
        ),
        (
            f"$|\\Delta S_z|$ (nm) & {_fmt(simple['classical']['abs_bias_Sz_nm'])} & {_fmt(simple['quantum_like']['abs_bias_Sz_nm'])} & {_fmt(rates['quantum_like']['abs_bias_Sz_nm'])} & {_fmt(nonideal['quantum_like']['abs_bias_Sz_nm'])} & {_fmt(simple['hybrid']['abs_bias_Sz_nm'])} & {_fmt(rates['hybrid']['abs_bias_Sz_nm'])} & {_fmt(nonideal['hybrid']['abs_bias_Sz_nm'])} " + row_end
        ),
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Measured-surface rate-model control for the paper benchmark")
    ap.add_argument("inputs", nargs="*", default=["data/*.sur"], help="SUR files or glob patterns under the repo root")
    ap.add_argument("--tag", type=str, default="paper_alicona_benchmark")
    ap.add_argument("--nx", type=int, default=256)
    ap.add_argument("--ny", type=int, default=256)
    ap.add_argument("--nreps", type=int, default=4)
    ap.add_argument("--jobs", type=int, default=0)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--skip-benchmark", action="store_true")
    ap.add_argument("--skip-base-reuse", action="store_true")
    ap.add_argument("--label", type=str, default="tab:benchmark_rate_model_control")
    ap.add_argument("--out-table", type=Path, default=Path("manuscript/tables/benchmark_rate_model_control.tex"))
    ap.add_argument("--gate-time-s", type=float, default=1e-3)
    ap.add_argument("--quant-target-mean-counts", type=float, default=3e4)
    ap.add_argument("--tau-c-s", type=float, default=20e-9)
    ap.add_argument("--eta1", type=float, default=0.70)
    ap.add_argument("--eta2", type=float, default=0.50)
    ap.add_argument("--deadtime-s", type=float, default=5e-9)
    args = ap.parse_args()

    root = _ROOT
    py = sys.executable
    out_base = root / "outputs" / str(args.tag)
    expanded_inputs = _expand_inputs(root, list(args.inputs))

    simple_per_surface = out_base / "per_surface.csv"
    if bool(args.skip_base_reuse):
        simple_per_surface = out_base / "rate_model_control" / "simple" / "per_surface.csv"

    if not simple_per_surface.exists() and not args.skip_benchmark:
        cmd = [
            py,
            str(root / "scripts" / "benchmark_sur_interferometry.py"),
            *expanded_inputs,
            "--outdir",
            str(simple_per_surface.parent),
            "--nx",
            str(int(args.nx)),
            "--ny",
            str(int(args.ny)),
            "--nreps",
            str(int(args.nreps)),
            "--jobs",
            str(int(args.jobs)),
        ]
        if int(args.limit) > 0:
            cmd.extend(["--limit", str(int(args.limit))])
        _run(cmd)

    rate_dir = out_base / "rate_model_control" / "rates"
    rate_nonideal_dir = out_base / "rate_model_control" / "rates_nonideal"
    common_rate_args = [
        py,
        str(root / "scripts" / "benchmark_sur_interferometry.py"),
        *expanded_inputs,
        "--nx",
        str(int(args.nx)),
        "--ny",
        str(int(args.ny)),
        "--nreps",
        str(int(args.nreps)),
        "--jobs",
        str(int(args.jobs)),
        "--quant-detector-model",
        "rates",
        "--gate-time-s",
        str(float(args.gate_time_s)),
        "--quant-target-mean-counts",
        str(float(args.quant_target_mean_counts)),
    ]

    if not args.skip_benchmark:
        rate_cmd = [
            *common_rate_args,
            "--outdir",
            str(rate_dir),
            "--tau-c-s",
            "0.0",
        ]
        nonideal_cmd = [
            *common_rate_args,
            "--outdir",
            str(rate_nonideal_dir),
            "--tau-c-s",
            str(float(args.tau_c_s)),
            "--eta1",
            str(float(args.eta1)),
            "--eta2",
            str(float(args.eta2)),
            "--deadtime1-s",
            str(float(args.deadtime_s)),
            "--deadtime2-s",
            str(float(args.deadtime_s)),
        ]
        if int(args.limit) > 0:
            rate_cmd.extend(["--limit", str(int(args.limit))])
            nonideal_cmd.extend(["--limit", str(int(args.limit))])
        _run(rate_cmd)
        _run(nonideal_cmd)

    summaries = {
        "simple": _summary_by_method(_collapse_surface_rows(_load_rows(simple_per_surface))),
        "rates": _summary_by_method(_collapse_surface_rows(_load_rows(rate_dir / "per_surface.csv"))),
        "rates_nonideal": _summary_by_method(_collapse_surface_rows(_load_rows(rate_nonideal_dir / "per_surface.csv"))),
    }

    summary_csv = out_base / "rate_model_control" / "summary.csv"
    _write_summary_csv(summary_csv, summaries)
    _write_latex_table(
        root / args.out_table,
        label=str(args.label),
        summaries=summaries,
        gate_time_ms=float(args.gate_time_s) * 1e3,
        tau_c_ns=float(args.tau_c_s) * 1e9,
        eta1=float(args.eta1),
        eta2=float(args.eta2),
        deadtime_ns=float(args.deadtime_s) * 1e9,
    )
    print(f"Wrote: {summary_csv}")
    print(f"Wrote: {root / args.out_table}")


if __name__ == "__main__":
    main()