#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from qiprof.metrics import detrend_plane, roughness_metrics
from qiprof.plot_style import apply_publication_style
from qiprof.reconstruct import height_from_phase, reconstruct_psi4, unwrap_2d_simple, unwrap_height_with_coarse
from qiprof.sim_classical import simulate_psi4
from qiprof.sim_quantum import simulate_coincidence_psi4
from qiprof.surfaces import make_surface


METHOD_ORDER = ["classical", "quantum_like", "hybrid"]
METHOD_LABEL = {
    "classical": "Classical",
    "quantum_like": "Q-noon2",
    "hybrid": "H-noon2",
}
SCENARIO_KEYS = ["low_return", "transition_high_return", "rough_high_return"]
SCENARIO_LABEL = {
    "low_return": "Low return / low visibility",
    "transition_high_return": "Transition high return",
    "rough_high_return": "Rough high return",
}
CONVENTION_LABEL = {
    "paper_default": "Paper default",
    "equal_nominal_quanta": "Equal nominal quanta",
    "equal_detected_counts": "Equal detected counts",
}

ROW_END = "\\\\"


def _rmse_nm(a_m: np.ndarray, b_m: np.ndarray) -> float:
    return float(np.sqrt(np.mean((a_m - b_m) ** 2)) * 1e9)


def _write_summary_csv(path: Path, rows: list[dict[str, float | str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError("No rows to write")
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_table(path: Path, rows: list[dict[str, float | str]], *, nreps: int, sq_true_nm: float) -> None:
    by_key = {(str(row["scenario"]), str(row["convention"]), str(row["method"])): row for row in rows}
    lines = [
        "% Auto-generated by scripts/run_paper_budget_sensitivity.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{Resource-normalisation sensitivity for three representative step-free NOON-like regimes. Entries report mean $\\pm$ std height RMSE over {int(nreps)} noise realisations. The scenarios span a low-return / low-visibility case, a high-return transition case, and a rougher high-return case; within each scenario the conventions compare the paper-default budget split, equal nominal source quanta per pixel, and matched detected counts in the coincidence proxy.}}",
        "\\label{tab:optprops_budget_sensitivity}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{llccc}",
        "\\toprule",
        "Scenario & Budget convention & Classical RMSE (nm) & Q-noon2 RMSE (nm) & H-noon2 RMSE (nm) " + ROW_END,
        "\\midrule",
    ]
    for scenario in SCENARIO_KEYS:
        scenario_rows = [row for row in rows if str(row["scenario"]) == scenario]
        if not scenario_rows:
            continue
        sq_scenario = float(scenario_rows[0]["Sq_true_nm"])
        reflectivity = float(scenario_rows[0]["sample_reflectivity"])
        visibility_scale = float(scenario_rows[0]["sample_visibility_scale"])
        scenario_label = (
            f"{SCENARIO_LABEL[scenario]} "
            f"($S_q\\approx {sq_scenario:.1f}$~nm, $R={reflectivity:.2f}$, $V_\\mathrm{{scale}}={visibility_scale:.2f}$)"
        )
        for idx, convention in enumerate(("paper_default", "equal_nominal_quanta", "equal_detected_counts")):
            row = [scenario_label if idx == 0 else "", f"{CONVENTION_LABEL[convention]}"]
            for method in METHOD_ORDER:
                vals = by_key[(scenario, convention, method)]
                row.append(f"${float(vals['rmse_mean_nm']):.2f} \\pm {float(vals['rmse_std_nm']):.2f}$")
            lines.append(" & ".join(row) + " " + ROW_END)
        lines.append("\\midrule")
    if lines[-1] == "\\midrule":
        lines.pop()
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _plot(path: Path, rows: list[dict[str, float | str]]) -> None:
    import matplotlib.pyplot as plt

    path.parent.mkdir(parents=True, exist_ok=True)
    apply_publication_style(base_fontsize=8.5)
    conventions = ["paper_default", "equal_nominal_quanta", "equal_detected_counts"]
    x = np.arange(len(conventions), dtype=float)
    width = 0.22
    styles = {
        "classical": ("#355070", -width),
        "quantum_like": ("#b56576", 0.0),
        "hybrid": ("#6d597a", width),
    }

    fig, axes = plt.subplots(1, len(SCENARIO_KEYS), figsize=(8.4, 2.9), constrained_layout=True, sharey=True)
    if len(SCENARIO_KEYS) == 1:
        axes = [axes]

    by_key = {(str(row["scenario"]), str(row["convention"]), str(row["method"])): row for row in rows}
    for ax, scenario in zip(axes, SCENARIO_KEYS):
        scenario_rows = [row for row in rows if str(row["scenario"]) == scenario]
        if not scenario_rows:
            continue
        sq_scenario = float(scenario_rows[0]["Sq_true_nm"])
        for method in METHOD_ORDER:
            color, offset = styles[method]
            ys = np.array([float(by_key[(scenario, conv, method)]["rmse_mean_nm"]) for conv in conventions], dtype=float)
            yerr = np.array([float(by_key[(scenario, conv, method)]["rmse_std_nm"]) for conv in conventions], dtype=float)
            ax.bar(
                x + offset,
                ys,
                width=width,
                color=color,
                label=METHOD_LABEL[method],
                yerr=yerr,
                capsize=2.5,
                alpha=0.9,
            )
        ax.set_xticks(x)
        ax.set_xticklabels(["Default", "Equal nominal", "Equal detected"], rotation=15, ha="right")
        ax.set_title(f"{SCENARIO_LABEL[scenario]}\n$S_q\\approx {sq_scenario:.0f}$ nm", fontsize=8.5)
        ax.grid(True, axis="y", alpha=0.25)
    axes[0].set_ylabel("Height RMSE (nm)")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, frameon=False, ncol=3, loc="upper center")
    fig.savefig(path)
    plt.close(fig)


def _convention_configs(args: argparse.Namespace) -> list[dict[str, float | str | None]]:
    return [
        {
            "name": "paper_default",
            "class_photons": float(args.class_photons),
            "quant_pairs": float(args.quant_pairs),
            "match_detected_counts": False,
        },
        {
            "name": "equal_nominal_quanta",
            "class_photons": float(args.quant_pairs),
            "quant_pairs": float(args.quant_pairs),
            "match_detected_counts": False,
        },
        {
            "name": "equal_detected_counts",
            "class_photons": float(args.class_photons),
            "quant_pairs": float(args.quant_pairs),
            "match_detected_counts": True,
        },
    ]


def _scenario_configs(args: argparse.Namespace) -> list[dict[str, float | str]]:
    labels = [item.strip() for item in str(args.scenario_labels).split(",") if item.strip()]
    rms_vals = [float(item.strip()) for item in str(args.scenario_rms_nm).split(",") if item.strip()]
    reflectivities = [float(item.strip()) for item in str(args.scenario_reflectivity).split(",") if item.strip()]
    visibilities = [float(item.strip()) for item in str(args.scenario_visibility_scale).split(",") if item.strip()]
    if not (len(labels) == len(rms_vals) == len(reflectivities) == len(visibilities) == len(SCENARIO_KEYS)):
        raise ValueError("Scenario labels, RMS values, reflectivities, and visibility scales must each define three entries")

    out: list[dict[str, float | str]] = []
    for key, label, rms_nm, reflectivity, visibility_scale in zip(
        SCENARIO_KEYS,
        labels,
        rms_vals,
        reflectivities,
        visibilities,
    ):
        out.append(
            {
                "key": key,
                "label": label,
                "rms_nm": rms_nm,
                "sample_reflectivity": reflectivity,
                "sample_visibility_scale": visibility_scale,
            }
        )
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Targeted resource-normalisation sensitivity for the paper")
    ap.add_argument("--outdir", type=Path, default=Path("outputs/paper_optprops/budget_sensitivity"))
    ap.add_argument("--table-out", type=Path, default=Path("manuscript/tables/optprops_budget_sensitivity.tex"))
    ap.add_argument("--nreps", type=int, default=10)
    ap.add_argument("--nx", type=int, default=256)
    ap.add_argument("--ny", type=int, default=256)
    ap.add_argument("--corr-len-um", type=float, default=25.0)
    ap.add_argument("--lambda-class-nm", type=float, default=532.0)
    ap.add_argument("--lambda1-nm", type=float, default=810.0)
    ap.add_argument("--lambda2-nm", type=float, default=809.0)
    ap.add_argument("--class-visibility", type=float, default=0.85)
    ap.add_argument("--class-photons", type=float, default=8e4)
    ap.add_argument("--quant-visibility", type=float, default=0.6)
    ap.add_argument("--quant-pairs", type=float, default=3e4)
    ap.add_argument("--hybrid-smooth-sigma-px", type=float, default=1.5)
    ap.add_argument(
        "--scenario-labels",
        type=str,
        default="Low return / low visibility,Transition high return,Rough high return",
    )
    ap.add_argument("--scenario-rms-nm", type=str, default="50,80,120")
    ap.add_argument("--scenario-reflectivity", type=str, default="0.20,1.00,1.00")
    ap.add_argument("--scenario-visibility-scale", type=str, default="0.70,1.00,1.00")
    args = ap.parse_args()

    outdir = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)

    lam_class = float(args.lambda_class_nm) * 1e-9
    lam1 = float(args.lambda1_nm) * 1e-9
    lam2 = float(args.lambda2_nm) * 1e-9
    rows: list[dict[str, float | str]] = []
    scenario_configs = _scenario_configs(args)
    for scenario in scenario_configs:
        h_true = make_surface(
            nx=int(args.nx),
            ny=int(args.ny),
            kind="gaussian_rough",
            rms=float(scenario["rms_nm"]) * 1e-9,
            corr_len=float(args.corr_len_um) * 1e-6,
            step_height=0.0,
            seed=0,
        ).h
        h_true_dt = detrend_plane(h_true)
        sq_true_nm = roughness_metrics(h_true).Sq * 1e9
        class_visibility_eff = float(np.clip(float(args.class_visibility) * float(scenario["sample_visibility_scale"]), 0.0, 1.0))
        quant_visibility_eff = float(np.clip(float(args.quant_visibility) * float(scenario["sample_visibility_scale"]), 0.0, 1.0))

        for convention in _convention_configs(args):
            rmse_by_method = {method: [] for method in METHOD_ORDER}
            for rep in range(int(args.nreps)):
                class_photons_eff = float(convention["class_photons"]) * float(scenario["sample_reflectivity"])
                quant_pairs_eff = float(convention["quant_pairs"]) * float(scenario["sample_reflectivity"])
                I4 = simulate_psi4(
                    h_true,
                    wavelength_m=lam_class,
                    visibility=class_visibility_eff,
                    photons_per_pixel=class_photons_eff,
                    phase_step_error_sigma_rad=0.0,
                    background_drift_frac=0.0,
                    amplitude_drift_frac=0.0,
                    seed=int(rep),
                )
                phi_w = reconstruct_psi4(I4)
                h_class = height_from_phase(unwrap_2d_simple(phi_w), wavelength_m=lam_class)
                target_mean_counts = float(np.mean(I4)) if bool(convention["match_detected_counts"]) else None
                C4 = simulate_coincidence_psi4(
                    h_true,
                    lambda1_m=lam1,
                    lambda2_m=lam2,
                    visibility=quant_visibility_eff,
                    pairs_per_pixel=quant_pairs_eff,
                    phase_step_error_sigma_rad=0.0,
                    background_drift_frac=0.0,
                    amplitude_drift_frac=0.0,
                    seed=int(rep),
                    interferometer="noon2",
                    detector_model="simple",
                    target_mean_counts_per_pixel=target_mean_counts,
                )
                phi_qw = reconstruct_psi4(C4)
                h_quant = height_from_phase(unwrap_2d_simple(phi_qw), wavelength_m=lam1 / 2.0)
                h_hybrid = unwrap_height_with_coarse(
                    phi_w,
                    coarse_height_m=h_quant,
                    wavelength_short_m=lam_class,
                    coarse_smooth_sigma_px=float(args.hybrid_smooth_sigma_px),
                )

                rmse_by_method["classical"].append(_rmse_nm(detrend_plane(h_class), h_true_dt))
                rmse_by_method["quantum_like"].append(_rmse_nm(detrend_plane(h_quant), h_true_dt))
                rmse_by_method["hybrid"].append(_rmse_nm(detrend_plane(h_hybrid), h_true_dt))

            for method, values in rmse_by_method.items():
                arr = np.array(values, dtype=float)
                rows.append(
                    {
                        "scenario": str(scenario["key"]),
                        "scenario_label": str(scenario["label"]),
                        "convention": str(convention["name"]),
                        "method": method,
                        "Sq_true_nm": float(sq_true_nm),
                        "sample_reflectivity": float(scenario["sample_reflectivity"]),
                        "sample_visibility_scale": float(scenario["sample_visibility_scale"]),
                        "class_photons": float(convention["class_photons"]),
                        "quant_pairs": float(convention["quant_pairs"]),
                        "matched_detected_counts": int(bool(convention["match_detected_counts"])),
                        "rmse_mean_nm": float(np.mean(arr)),
                        "rmse_std_nm": float(np.std(arr, ddof=1)) if arr.size > 1 else 0.0,
                    }
                )

    summary_path = outdir / "summary.csv"
    figure_path = outdir / "budget_sensitivity.pdf"
    _write_summary_csv(summary_path, rows)
    _write_table(args.table_out, rows, nreps=int(args.nreps), sq_true_nm=0.0)
    _plot(figure_path, rows)
    print(f"Wrote summary: {summary_path}")
    print(f"Wrote figure:  {figure_path}")
    print(f"Wrote table:   {args.table_out}")


if __name__ == "__main__":
    main()