#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from qiprof.labels import decode_sur_stem
from qiprof.surfaces import read_digital_surf_sur_header


def _unit_to_m(unit: str) -> float:
    u = unit.strip().lower().replace("µ", "u")
    if u in {"m", "meter", "metre"}:
        return 1.0
    if u == "mm":
        return 1e-3
    if u in {"um", "micrometer", "micrometre"}:
        return 1e-6
    if u == "nm":
        return 1e-9
    raise ValueError(f"Unsupported unit in .sur header: {unit!r}")


def _expand_inputs(root: Path, patterns: list[str]) -> list[Path]:
    out: list[Path] = []
    seen: set[Path] = set()
    for pattern in patterns:
        candidate = (root / pattern).resolve()
        if candidate.exists():
            if candidate not in seen:
                out.append(candidate)
                seen.add(candidate)
            continue
        for match in sorted(root.glob(pattern)):
            resolved = match.resolve()
            if resolved not in seen:
                out.append(resolved)
                seen.add(resolved)
    if not out:
        raise FileNotFoundError(f"No input surfaces matched: {patterns}")
    return out


def _fmt_range(values: list[float], *, scale: float, digits: int, suffix: str) -> str:
    lo = min(values) * scale
    hi = max(values) * scale
    fmt = f"{{:.{digits}f}}"
    if abs(lo - hi) < 10 ** (-digits):
        return f"${fmt.format(lo)}$ {suffix}"
    return f"${fmt.format(lo)}$--${fmt.format(hi)}$ {suffix}"


def _fmt_grid(nx_values: list[int], ny_values: list[int]) -> str:
    nx_lo, nx_hi = min(nx_values), max(nx_values)
    ny_lo, ny_hi = min(ny_values), max(ny_values)
    if nx_lo == nx_hi and ny_lo == ny_hi:
        return f"${nx_lo} \\times {ny_lo}$ px"
    return f"${nx_lo}$--${nx_hi}$ by ${ny_lo}$--${ny_hi}$ px"


def _write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    fieldnames = [
        "file",
        "stem",
        "material",
        "treatment",
        "orig_nx",
        "orig_ny",
        "size_x_m",
        "size_y_m",
        "dx_m",
        "dy_m",
        "z_unit",
        "bytes_per_point",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_table(path: Path, *, rows: list[dict[str, object]], target_nx: int, target_ny: int) -> None:
    materials = sorted({str(row["material"]) for row in rows})
    treatments = sorted({str(row["treatment"]) for row in rows})
    nx_values = [int(row["orig_nx"]) for row in rows]
    ny_values = [int(row["orig_ny"]) for row in rows]
    size_x_values = [float(row["size_x_m"]) for row in rows]
    size_y_values = [float(row["size_y_m"]) for row in rows]
    dx_values = [float(row["dx_m"]) for row in rows]
    dy_values = [float(row["dy_m"]) for row in rows]
    z_units = sorted({str(row["z_unit"]) for row in rows})
    bytes_per_point = sorted({int(row["bytes_per_point"]) for row in rows})

    material_list = ", ".join(materials)
    treatment_list = ", ".join(treatments)
    z_unit_value = ", ".join(z_units)
    bpp_value = ", ".join(str(value) for value in bytes_per_point)

    table_rows = [
        ("Measured surfaces", f"${len(rows)}$"),
        ("Material groups", f"${len(materials)}$: {material_list}"),
        ("Treatment classes", f"${len(treatments)}$: {treatment_list}"),
        ("Native lateral grid", _fmt_grid(nx_values, ny_values)),
        ("Lateral field of view in $x$", _fmt_range(size_x_values, scale=1e3, digits=2, suffix="mm")),
        ("Lateral field of view in $y$", _fmt_range(size_y_values, scale=1e3, digits=2, suffix="mm")),
        ("Native lateral pitch in $x$", _fmt_range(dx_values, scale=1e6, digits=2, suffix="µm")),
        ("Native lateral pitch in $y$", _fmt_range(dy_values, scale=1e6, digits=2, suffix="µm")),
        ("Encoded height unit", z_unit_value),
        ("Stored bytes per point", bpp_value),
        ("Benchmark simulation grid", f"Area-averaged to ${int(target_nx)} \\times {int(target_ny)}$ px before forward simulation"),
    ]

    lines = [
        "% Auto-generated by scripts/run_paper_surface_metadata.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\caption{Dataset-level summary of the Mountains/DigitalSurf header metadata for the measured focus-variation surfaces used in the paper benchmark. Lateral extents and native sampling pitch are reported after conversion to common SI-derived units; the final row records the fixed area-averaged benchmark grid used by the forward interferometer simulations.} ",
        "\\label{tab:measured_surface_metadata}",
        "\\begin{tabularx}{\\textwidth}{lX}",
        "\\toprule",
            "Descriptor & Value \\\\",
        "\\midrule",
    ]
    for label, value in table_rows:
        lines.append(f"{label} & {value} \\\\")
    lines.extend([
        "\\bottomrule",
        "\\end{tabularx}",
        "\\end{table}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Create manuscript-facing measured-surface metadata artefacts from SUR headers")
    ap.add_argument("inputs", nargs="*", default=["data/*.sur"], help="SUR files or glob patterns under the repo root")
    ap.add_argument("--tag", type=str, default="paper_alicona_benchmark")
    ap.add_argument("--target-nx", type=int, default=256)
    ap.add_argument("--target-ny", type=int, default=256)
    ap.add_argument(
        "--out-table",
        type=Path,
        default=Path("manuscript/tables/measured_surface_metadata.tex"),
    )
    args = ap.parse_args()

    root = _ROOT
    inputs = _expand_inputs(root, list(args.inputs))
    rows: list[dict[str, object]] = []
    for path in inputs:
        hdr = read_digital_surf_sur_header(path)
        decoded = decode_sur_stem(path.stem)
        size_x_m = float(hdr.size_x) * _unit_to_m(hdr.size_unit_x)
        size_y_m = float(hdr.size_y) * _unit_to_m(hdr.size_unit_y)
        rows.append(
            {
                "file": str(path.relative_to(root).as_posix()),
                "stem": path.stem,
                "material": decoded.material_en,
                "treatment": decoded.treatment_en,
                "orig_nx": int(hdr.nx),
                "orig_ny": int(hdr.ny),
                "size_x_m": size_x_m,
                "size_y_m": size_y_m,
                "dx_m": size_x_m / max(int(hdr.nx), 1),
                "dy_m": size_y_m / max(int(hdr.ny), 1),
                "z_unit": hdr.z_unit,
                "bytes_per_point": int(hdr.bytes_per_point),
            }
        )

    outdir = root / "outputs" / str(args.tag) / "surface_metadata"
    _write_csv(outdir / "per_surface.csv", rows)
    _write_table(root / args.out_table, rows=rows, target_nx=int(args.target_nx), target_ny=int(args.target_ny))
    print(f"Wrote: {outdir / 'per_surface.csv'}")
    print(f"Wrote: {root / args.out_table}")


if __name__ == "__main__":
    main()