#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from pathlib import Path
import sys

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from qiprof.metrics import detrend_plane, roughness_metrics
from qiprof.plot_style import apply_publication_style
from qiprof.reconstruct import height_from_phase, reconstruct_psi4, unwrap_2d_simple, unwrap_height_with_coarse
from qiprof.sim_classical import simulate_psi4
from qiprof.sim_quantum import effective_wavelength, simulate_coincidence_psi4
from qiprof.surfaces import make_surface


def _coherence_factor(*, rms_m: float, wavelength_m: float, model: str, incidence_cos: float = 1.0) -> float:
    name = model.strip().lower().replace("-", "_")
    if name in {"none", "off", "0"}:
        return 1.0
    if name in {"rayleigh", "roughness", "specular"}:
        c = float(np.clip(incidence_cos, 0.0, 1.0))
        x = (4.0 * np.pi * float(rms_m) * c) / float(wavelength_m)
        return float(np.exp(-(x * x)))
    raise ValueError("coherence-model must be one of: none, rayleigh")


def _rmse_nm(a_m: np.ndarray, b_m: np.ndarray) -> float:
    return float(np.sqrt(np.mean((a_m - b_m) ** 2)) * 1e9)


def _write_summary_csv(path: Path, rows: list[dict[str, float | str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError("No rows to write")
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_table(path: Path, rows: list[dict[str, float | str]], *, nreps: int) -> None:
    vis_scales = sorted({float(row["sample_visibility_scale"]) for row in rows})
    by_vis_delta_method = {
        (float(row["sample_visibility_scale"]), float(row["delta_lambda_nm"]), str(row["method"])): row
        for row in rows
    }

    lines = [
        "% Auto-generated by scripts/run_paper_lambda_visibility_sensitivity.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{Targeted wavelength-spacing and visibility sensitivity for a representative step-free rough surface ($S_q\\approx 80$~nm) under the same cosine--Poisson proxy model used in the synthetic sweeps. Entries report mean $\\pm$ std height RMSE over {int(nreps)} noise realisations. The nominal paper operating point corresponds to $\\Delta\\lambda=1.0$~nm (810/809).}}",
        "\\label{tab:optprops_lambda_sensitivity}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{ccccc}",
        "\\toprule",
        "Visibility scale & $\\Delta\\lambda$ (nm) & $\\Lambda_{\\mathrm{eff}}$ ($\\mu$m) & Classical RMSE (nm) & Quantum-like / Hybrid RMSE (nm) \\\\",
        "\\midrule",
    ]

    for vis_scale in vis_scales:
        delta_values = sorted({float(row["delta_lambda_nm"]) for row in rows if float(row["sample_visibility_scale"]) == vis_scale})
        first_row = True
        for delta_lambda_nm in delta_values:
            classical = by_vis_delta_method[(vis_scale, delta_lambda_nm, "classical")]
            quant = by_vis_delta_method[(vis_scale, delta_lambda_nm, "quantum_like")]
            hybrid = by_vis_delta_method[(vis_scale, delta_lambda_nm, "hybrid")]
            vis_label = f"${vis_scale:.2f}$" if first_row else ""
            qh = (
                f"$Q$: ${float(quant['rmse_mean_nm']):.1f} \\pm {float(quant['rmse_std_nm']):.1f}$; "
                f"$H$: ${float(hybrid['rmse_mean_nm']):.1f} \\pm {float(hybrid['rmse_std_nm']):.1f}$"
            )
            row = " & ".join(
                [
                    vis_label,
                    f"${delta_lambda_nm:.1f}$",
                    f"${float(classical['lambda_eff_um']):.1f}$",
                    f"${float(classical['rmse_mean_nm']):.1f} \\pm {float(classical['rmse_std_nm']):.1f}$",
                    qh,
                ]
            )
            lines.append(row + " " + chr(92) + chr(92))
            first_row = False
        lines.append("\\midrule")

    if lines[-1] == "\\midrule":
        lines.pop()

    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _plot(path: Path, rows: list[dict[str, float | str]]) -> None:
    import matplotlib.pyplot as plt

    path.parent.mkdir(parents=True, exist_ok=True)
    apply_publication_style(base_fontsize=8.5)

    vis_scales = sorted({float(row["sample_visibility_scale"]) for row in rows})
    fig, axes = plt.subplots(1, len(vis_scales), figsize=(6.77, 2.65), sharey=True, constrained_layout=True)
    if len(vis_scales) == 1:
        axes = [axes]

    method_styles = {
        "classical": {"color": "#355070", "label": "Classical", "linestyle": "--"},
        "quantum_like": {"color": "#b56576", "label": "Quantum-like diff", "linestyle": "-"},
        "hybrid": {"color": "#6d597a", "label": "Hybrid diff", "linestyle": "-"},
    }

    for ax, vis_scale in zip(axes, vis_scales):
        subset = [row for row in rows if float(row["sample_visibility_scale"]) == vis_scale]
        delta_values = np.array(sorted({float(row["delta_lambda_nm"]) for row in subset}), dtype=float)
        for method in ("classical", "quantum_like", "hybrid"):
            method_rows = {
                float(row["delta_lambda_nm"]): row
                for row in subset
                if str(row["method"]) == method
            }
            ys = np.array([float(method_rows[delta]["rmse_mean_nm"]) for delta in delta_values], dtype=float)
            yerr = np.array([float(method_rows[delta]["rmse_std_nm"]) for delta in delta_values], dtype=float)
            ax.errorbar(
                delta_values,
                ys,
                yerr=yerr,
                marker="o",
                markersize=3.8,
                linewidth=1.2,
                capsize=2.0,
                color=method_styles[method]["color"],
                linestyle=method_styles[method]["linestyle"],
                label=method_styles[method]["label"],
            )
        ax.axvline(1.0, color="0.35", linestyle=":", linewidth=0.9)
        ax.set_yscale("log")
        ax.set_xlabel("$\\Delta\\lambda$ (nm)")
        ax.set_title(f"Visibility scale = {vis_scale:.2f}")
        ax.grid(True, which="both", alpha=0.25)

    axes[0].set_ylabel("Height RMSE (nm) [log]")
    axes[0].legend(frameon=False, loc="upper right")
    fig.savefig(path)
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser(description="Targeted wavelength-spacing and visibility sensitivity control for the paper")
    ap.add_argument("--outdir", type=Path, default=Path("outputs/paper_optprops/lambda_spacing_control"))
    ap.add_argument("--table-out", type=Path, default=Path("manuscript/tables/optprops_lambda_sensitivity.tex"))
    ap.add_argument("--nreps", type=int, default=10)
    ap.add_argument("--nx", type=int, default=256)
    ap.add_argument("--ny", type=int, default=256)
    ap.add_argument("--rms-nm", type=float, default=80.0)
    ap.add_argument("--corr-len-um", type=float, default=25.0)
    ap.add_argument("--lambda-class-nm", type=float, default=532.0)
    ap.add_argument("--lambda1-nm", type=float, default=810.0)
    ap.add_argument("--delta-lambda-nm", type=float, nargs="*", default=[0.2, 0.5, 1.0, 2.0])
    ap.add_argument("--sample-visibility-scale", type=float, nargs="*", default=[0.7, 1.0])
    ap.add_argument("--class-visibility", type=float, default=0.85)
    ap.add_argument("--class-photons", type=float, default=8e4)
    ap.add_argument("--quant-visibility", type=float, default=0.6)
    ap.add_argument("--quant-pairs", type=float, default=3e4)
    ap.add_argument("--coherence-model", type=str, default="rayleigh", choices=["none", "rayleigh"])
    ap.add_argument("--incidence-cos", type=float, default=1.0)
    ap.add_argument("--hybrid-smooth-sigma-px", type=float, default=1.5)
    args = ap.parse_args()

    outdir = args.outdir
    outdir.mkdir(parents=True, exist_ok=True)

    lam_class = float(args.lambda_class_nm) * 1e-9
    lam1 = float(args.lambda1_nm) * 1e-9
    rms_m = float(args.rms_nm) * 1e-9
    h_true = make_surface(
        nx=int(args.nx),
        ny=int(args.ny),
        kind="gaussian_rough",
        rms=rms_m,
        corr_len=float(args.corr_len_um) * 1e-6,
        step_height=0.0,
        seed=0,
    ).h
    h_true_dt = detrend_plane(h_true)
    sq_true_nm = roughness_metrics(h_true).Sq * 1e9
    phase_step_sigma_rad = 0.0

    rows: list[dict[str, float | str]] = []
    for vis_scale in [float(v) for v in args.sample_visibility_scale]:
        coh_class = _coherence_factor(
            rms_m=rms_m,
            wavelength_m=lam_class,
            model=str(args.coherence_model),
            incidence_cos=float(args.incidence_cos),
        )
        class_visibility_eff = float(np.clip(float(args.class_visibility) * vis_scale * coh_class, 0.0, 1.0))
        for delta_lambda_nm in [float(v) for v in args.delta_lambda_nm]:
            lam2 = (float(args.lambda1_nm) - delta_lambda_nm) * 1e-9
            if lam2 <= 0.0:
                raise ValueError("lambda2 must remain positive")
            lam_eff = effective_wavelength(interferometer="diff", lambda1_m=lam1, lambda2_m=lam2)
            coh_quant = _coherence_factor(
                rms_m=rms_m,
                wavelength_m=0.5 * (lam1 + lam2),
                model=str(args.coherence_model),
                incidence_cos=float(args.incidence_cos),
            )
            quant_visibility_eff = float(np.clip(float(args.quant_visibility) * vis_scale * coh_quant, 0.0, 1.0))

            rmse_by_method = {"classical": [], "quantum_like": [], "hybrid": []}
            for rep in range(int(args.nreps)):
                I4 = simulate_psi4(
                    h_true,
                    wavelength_m=lam_class,
                    visibility=class_visibility_eff,
                    photons_per_pixel=float(args.class_photons),
                    phase_step_error_sigma_rad=phase_step_sigma_rad,
                    background_drift_frac=0.0,
                    amplitude_drift_frac=0.0,
                    seed=int(rep),
                )
                phi_w = reconstruct_psi4(I4)
                h_class = height_from_phase(unwrap_2d_simple(phi_w), wavelength_m=lam_class)

                C4 = simulate_coincidence_psi4(
                    h_true,
                    lambda1_m=lam1,
                    lambda2_m=lam2,
                    visibility=quant_visibility_eff,
                    pairs_per_pixel=float(args.quant_pairs),
                    phase_step_error_sigma_rad=phase_step_sigma_rad,
                    background_drift_frac=0.0,
                    amplitude_drift_frac=0.0,
                    seed=int(rep),
                    interferometer="diff",
                    detector_model="simple",
                )
                phi_qw = reconstruct_psi4(C4)
                h_quant = height_from_phase(unwrap_2d_simple(phi_qw), wavelength_m=lam_eff)
                h_hybrid = unwrap_height_with_coarse(
                    phi_w,
                    coarse_height_m=h_quant,
                    wavelength_short_m=lam_class,
                    coarse_smooth_sigma_px=float(args.hybrid_smooth_sigma_px),
                )

                rmse_by_method["classical"].append(_rmse_nm(detrend_plane(h_class), h_true_dt))
                rmse_by_method["quantum_like"].append(_rmse_nm(detrend_plane(h_quant), h_true_dt))
                rmse_by_method["hybrid"].append(_rmse_nm(detrend_plane(h_hybrid), h_true_dt))

            for method, values in rmse_by_method.items():
                arr = np.array(values, dtype=float)
                rows.append(
                    {
                        "sample_visibility_scale": vis_scale,
                        "Sq_true_nm": sq_true_nm,
                        "lambda1_nm": float(args.lambda1_nm),
                        "lambda2_nm": float(args.lambda1_nm) - delta_lambda_nm,
                        "delta_lambda_nm": delta_lambda_nm,
                        "lambda_eff_um": lam_eff * 1e6,
                        "coherence_model": str(args.coherence_model),
                        "method": method,
                        "rmse_mean_nm": float(np.mean(arr)),
                        "rmse_std_nm": float(np.std(arr, ddof=1)) if arr.size > 1 else 0.0,
                    }
                )

    summary_path = outdir / "summary.csv"
    figure_path = outdir / "rmse_vs_delta_lambda.pdf"
    _write_summary_csv(summary_path, rows)
    _write_table(args.table_out, rows, nreps=int(args.nreps))
    _plot(figure_path, rows)
    print(f"Wrote summary: {summary_path}")
    print(f"Wrote figure:  {figure_path}")
    print(f"Wrote table:   {args.table_out}")


if __name__ == "__main__":
    main()