#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
import subprocess
import sys

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT / "src"))

from qiprof.plot_style import apply_publication_style


SCENARIOS = [
    {
        "key": "low_return",
        "label": "Low return / low visibility",
        "sample_reflectivity": 0.20,
        "sample_visibility_scale": 0.70,
    },
    {
        "key": "high_return",
        "label": "High return / high visibility",
        "sample_reflectivity": 1.00,
        "sample_visibility_scale": 1.00,
    },
]

METHOD_ORDER = ["classical", "quant_diff", "hybrid_diff", "quant_noon2", "hybrid_noon2"]
METHOD_LABEL = {
    "classical": "Classical",
    "quant_diff": "Q-diff",
    "hybrid_diff": "H-diff",
    "quant_noon2": "Q-noon2",
    "hybrid_noon2": "H-noon2",
}


def _run(cmd: list[str]) -> None:
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def _write_summary_csv(path: Path, rows: list[dict[str, float | str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        raise ValueError("No rows to write")
    fieldnames = list(rows[0].keys())
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _summarise_rows(rows: list[dict[str, str]], *, scenario: dict[str, float | str]) -> list[dict[str, float | str]]:
    grouped: dict[tuple[float, str], list[float]] = defaultdict(list)
    for row in rows:
        method = str(row["method"])
        if method not in METHOD_ORDER:
            continue
        grouped[(float(row["step_nm"]), method)].append(abs(float(row["step_err_nm"])))

    summary_rows: list[dict[str, float | str]] = []
    for step_nm in sorted({key[0] for key in grouped}):
        for method in METHOD_ORDER:
            values = np.array(grouped[(step_nm, method)], dtype=float)
            summary_rows.append(
                {
                    "scenario": str(scenario["key"]),
                    "scenario_label": str(scenario["label"]),
                    "sample_reflectivity": float(scenario["sample_reflectivity"]),
                    "sample_visibility_scale": float(scenario["sample_visibility_scale"]),
                    "step_nm": float(step_nm),
                    "method": method,
                    "abs_step_err_mean_nm": float(np.mean(values)),
                    "abs_step_err_std_nm": float(np.std(values, ddof=1)) if values.size > 1 else 0.0,
                }
            )
    return summary_rows


def _fmt(value: float) -> str:
    return f"${value:.1f}$"


def _write_table(path: Path, rows: list[dict[str, float | str]], *, label: str, nreps: int, rms_nm: float) -> None:
    by_key = {(str(row["scenario"]), float(row["step_nm"]), str(row["method"])): row for row in rows}
    row_end = "\\\\"
    lines = [
        "% Auto-generated by scripts/run_paper_step_regime_control.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        f"\\caption{{Targeted ambiguity-regime control for a rough step surface with background roughness $S_q\\approx {float(rms_nm):.0f}$~nm. Entries report mean $\\pm$ std absolute step-height error over {int(nreps)} noise realisations while the imposed step height is varied. The two blocks bracket the low-return / low-visibility and high-return / high-visibility conditions used elsewhere in the paper.}}",
        f"\\label{{{label}}}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{llccccc}",
        "\\toprule",
        "Scenario & Step height (nm) & Classical & Q-diff & H-diff & Q-noon2 & H-noon2 " + row_end,
        "\\midrule",
    ]
    for scenario in SCENARIOS:
        scenario_rows = [row for row in rows if str(row["scenario"]) == str(scenario["key"])]
        if not scenario_rows:
            continue
        steps = sorted({float(row["step_nm"]) for row in scenario_rows})
        scenario_label = (
            f"{scenario['label']} ($R={float(scenario['sample_reflectivity']):.2f}$, "
            f"$V_\\mathrm{{scale}}={float(scenario['sample_visibility_scale']):.2f}$)"
        )
        for idx, step_nm in enumerate(steps):
            row = [scenario_label if idx == 0 else "", f"{step_nm:.0f}"]
            for method in METHOD_ORDER:
                vals = by_key[(str(scenario["key"]), float(step_nm), method)]
                row.append(
                    f"${float(vals['abs_step_err_mean_nm']):.1f} \\pm {float(vals['abs_step_err_std_nm']):.1f}$"
                )
            lines.append(" & ".join(row) + " " + row_end)
        lines.append("\\midrule")
    if lines[-1] == "\\midrule":
        lines.pop()
    lines.extend([
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table}",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def _plot(path: Path, rows: list[dict[str, float | str]]) -> None:
    import matplotlib.pyplot as plt

    path.parent.mkdir(parents=True, exist_ok=True)
    apply_publication_style(base_fontsize=8.5)
    styles = {
        "classical": "#355070",
        "quant_diff": "#6d597a",
        "hybrid_diff": "#eaac8b",
        "quant_noon2": "#b56576",
        "hybrid_noon2": "#2a9d8f",
    }

    fig, axes = plt.subplots(1, len(SCENARIOS), figsize=(8.2, 3.2), constrained_layout=False, sharey=True)
    if len(SCENARIOS) == 1:
        axes = [axes]

    by_key = {(str(row["scenario"]), float(row["step_nm"]), str(row["method"])): row for row in rows}
    for ax, scenario in zip(axes, SCENARIOS):
        scenario_rows = [row for row in rows if str(row["scenario"]) == str(scenario["key"])]
        if not scenario_rows:
            continue
        steps = sorted({float(row["step_nm"]) for row in scenario_rows})
        for method in METHOD_ORDER:
            ys = np.array([float(by_key[(str(scenario["key"]), step_nm, method)]["abs_step_err_mean_nm"]) for step_nm in steps])
            yerr = np.array([float(by_key[(str(scenario["key"]), step_nm, method)]["abs_step_err_std_nm"]) for step_nm in steps])
            ax.errorbar(
                steps,
                ys,
                yerr=yerr,
                marker="o",
                linewidth=1.15,
                elinewidth=1.0,
                capsize=2.5,
                markersize=3.2,
                label=METHOD_LABEL[method],
                color=styles[method],
                alpha=0.95,
            )
        ax.set_title(
            f"{scenario['label']}\n$R={float(scenario['sample_reflectivity']):.2f}$, "
            f"$V_\\mathrm{{scale}}={float(scenario['sample_visibility_scale']):.2f}$",
            fontsize=8.5,
            pad=6.0,
        )
        ax.set_xlabel("Step height (nm)")
        ax.grid(True, alpha=0.25)
    axes[0].set_ylabel("Absolute step-height error (nm)")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        frameon=False,
        ncol=len(METHOD_ORDER),
        loc="upper center",
        bbox_to_anchor=(0.5, 0.99),
        columnspacing=1.2,
        handletextpad=0.5,
        fontsize=8.0,
    )
    fig.tight_layout(rect=(0.0, 0.0, 1.0, 0.82))
    fig.savefig(path)
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser(description="Paper step/ambiguity control for the optical-property sweep")
    ap.add_argument("--tag", type=str, default="paper_optprops_step_regime", help="Output tag under outputs/")
    ap.add_argument("--nx", type=int, default=128)
    ap.add_argument("--ny", type=int, default=128)
    ap.add_argument("--nreps", type=int, default=10)
    ap.add_argument("--rms-nm", type=float, default=80.0)
    ap.add_argument("--corr-len-um", type=float, default=25.0)
    ap.add_argument("--step-nm-list", type=str, default="0,100,200,300,400,600,800")
    ap.add_argument("--table-out", type=Path, default=Path("manuscript/tables/optprops_step_sensitivity.tex"))
    ap.add_argument("--label", type=str, default="tab:optprops_step_sensitivity")
    args = ap.parse_args()

    root = _ROOT
    py = sys.executable
    out_base = root / "outputs" / str(args.tag)
    steps = [item.strip() for item in str(args.step_nm_list).split(",") if item.strip()]

    all_rows: list[dict[str, float | str]] = []
    for scenario in SCENARIOS:
        scenario_out = out_base / str(scenario["key"])
        _run(
            [
                py,
                str(root / "scripts" / "run_sweep.py"),
                "--outdir",
                str(scenario_out / "sweep"),
                "--nx",
                str(int(args.nx)),
                "--ny",
                str(int(args.ny)),
                "--nreps",
                str(int(args.nreps)),
                "--rms-nm",
                str(float(args.rms_nm)),
                "--step-nm",
                *steps,
                "--corr-len-um",
                str(float(args.corr_len_um)),
                "--sample-reflectivity",
                str(float(scenario["sample_reflectivity"])),
                "--sample-visibility-scale",
                str(float(scenario["sample_visibility_scale"])),
                "--quant-interferometer",
                "diff",
                "noon2",
                "--coherence-model",
                "rayleigh",
                "--no-surface-fig",
            ]
        )
        rows = _load_rows(scenario_out / "sweep" / "sweep.csv")
        all_rows.extend(_summarise_rows(rows, scenario=scenario))

    summary_csv = out_base / "summary.csv"
    figure_path = out_base / "step_regime_summary.pdf"
    _write_summary_csv(summary_csv, all_rows)
    _write_table(root / args.table_out, all_rows, label=str(args.label), nreps=int(args.nreps), rms_nm=float(args.rms_nm))
    _plot(figure_path, all_rows)
    print(f"Wrote summary: {summary_csv}")
    print(f"Wrote figure:  {figure_path}")
    print(f"Wrote table:   {root / args.table_out}")


if __name__ == "__main__":
    main()