#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
import subprocess
import sys

import numpy as np

_ROOT = Path(__file__).resolve().parents[1]


def _run(cmd: list[str]) -> None:
    print(" ".join(cmd))
    subprocess.run(cmd, check=True)


def _expand_inputs(root: Path, patterns: list[str]) -> list[str]:
    out: list[str] = []
    seen: set[Path] = set()
    for pattern in patterns:
        candidate = (root / pattern).resolve()
        if candidate.exists():
            if candidate not in seen:
                out.append(str(candidate))
                seen.add(candidate)
            continue
        matches = sorted(root.glob(pattern))
        for match in matches:
            resolved = match.resolve()
            if resolved not in seen:
                out.append(str(resolved))
                seen.add(resolved)
    if not out:
        raise FileNotFoundError(f"No input surfaces matched: {patterns}")
    return out


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No rows found in {path}")
    return rows


def _collapse_surface_rows(rows: list[dict[str, str]]) -> list[dict[str, float | str]]:
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[(row["stem"], row["method"])].append(row)

    out: list[dict[str, float | str]] = []
    for (stem, method), entries in sorted(grouped.items()):
        out.append(
            {
                "stem": stem,
                "method": method,
                "height_rmse_nm": float(np.median([float(e["height_rmse_nm"]) for e in entries])),
                "abs_bias_Sa_nm": float(np.median([abs(float(e["bias_Sa_nm"])) for e in entries])),
                "abs_bias_Sq_nm": float(np.median([abs(float(e["bias_Sq_nm"])) for e in entries])),
                "abs_bias_Sz_nm": float(np.median([abs(float(e["bias_Sz_nm"])) for e in entries])),
            }
        )
    return out


def _summary_by_method(rows: list[dict[str, float | str]]) -> dict[str, dict[str, float]]:
    out: dict[str, dict[str, float]] = {}
    for method in {str(row["method"]) for row in rows}:
        mrows = [row for row in rows if str(row["method"]) == method]
        out[method] = {
            "height_rmse_nm": float(np.median([float(row["height_rmse_nm"]) for row in mrows])),
            "abs_bias_Sa_nm": float(np.median([float(row["abs_bias_Sa_nm"]) for row in mrows])),
            "abs_bias_Sq_nm": float(np.median([float(row["abs_bias_Sq_nm"]) for row in mrows])),
            "abs_bias_Sz_nm": float(np.median([float(row["abs_bias_Sz_nm"]) for row in mrows])),
        }
    return out


def _write_summary_csv(path: Path, simple: dict[str, dict[str, float]], least_squares: dict[str, dict[str, float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = ["unwrap_method", "method", "height_rmse_nm", "abs_bias_Sa_nm", "abs_bias_Sq_nm", "abs_bias_Sz_nm"]
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for unwrap_method, summary in [("simple", simple), ("least_squares", least_squares)]:
            for method, vals in summary.items():
                writer.writerow({"unwrap_method": unwrap_method, "method": method, **vals})


def _fmt(value: float) -> str:
    return f"${value:.1f}$"


def _write_latex_table(path: Path, *, label: str, simple: dict[str, dict[str, float]], least_squares: dict[str, dict[str, float]]) -> None:
    lines = [
        "% Auto-generated by scripts/run_paper_unwrap_control.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\footnotesize",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\caption{Measured-surface unwrapping control over the full benchmark dataset. Direct classical and quantum-like branches are rerun with a global least-squares Poisson unwrap instead of the default separable row/column unwrap; entries report surface-level medians after collapsing repeated runs within each surface and method. The hybrid branch is unchanged because it uses the coincidence-derived coarse prior directly for fringe-order assignment.}",
        f"\\label{{{label}}}",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "Endpoint & Classical (simple) & Classical (least-squares) & Quantum-like (simple) & Quantum-like (least-squares) & Hybrid \\\\",
        "\\midrule",
        f"Height RMSE (nm) & {_fmt(simple['classical']['height_rmse_nm'])} & {_fmt(least_squares['classical']['height_rmse_nm'])} & {_fmt(simple['quantum_like']['height_rmse_nm'])} & {_fmt(least_squares['quantum_like']['height_rmse_nm'])} & {_fmt(simple['hybrid']['height_rmse_nm'])} \\\\",
        f"$|\\Delta S_a|$ (nm) & {_fmt(simple['classical']['abs_bias_Sa_nm'])} & {_fmt(least_squares['classical']['abs_bias_Sa_nm'])} & {_fmt(simple['quantum_like']['abs_bias_Sa_nm'])} & {_fmt(least_squares['quantum_like']['abs_bias_Sa_nm'])} & {_fmt(simple['hybrid']['abs_bias_Sa_nm'])} \\\\",
        f"$|\\Delta S_q|$ (nm) & {_fmt(simple['classical']['abs_bias_Sq_nm'])} & {_fmt(least_squares['classical']['abs_bias_Sq_nm'])} & {_fmt(simple['quantum_like']['abs_bias_Sq_nm'])} & {_fmt(least_squares['quantum_like']['abs_bias_Sq_nm'])} & {_fmt(simple['hybrid']['abs_bias_Sq_nm'])} \\\\",
        f"$|\\Delta S_z|$ (nm) & {_fmt(simple['classical']['abs_bias_Sz_nm'])} & {_fmt(least_squares['classical']['abs_bias_Sz_nm'])} & {_fmt(simple['quantum_like']['abs_bias_Sz_nm'])} & {_fmt(least_squares['quantum_like']['abs_bias_Sz_nm'])} & {_fmt(simple['hybrid']['abs_bias_Sz_nm'])} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "}%",
        "\\end{table}",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser(description="Targeted measured-benchmark unwrap control")
    ap.add_argument("inputs", nargs="*", default=["data/*.sur"], help="SUR files or glob patterns under the repo root")
    ap.add_argument("--tag", type=str, default="paper_alicona_benchmark")
    ap.add_argument("--nx", type=int, default=256)
    ap.add_argument("--ny", type=int, default=256)
    ap.add_argument("--nreps", type=int, default=1)
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--skip-benchmark", action="store_true")
    ap.add_argument("--skip-base-reuse", action="store_true")
    ap.add_argument("--label", type=str, default="tab:benchmark_unwrap_control")
    ap.add_argument(
        "--out-table",
        type=Path,
        default=Path("manuscript/tables/benchmark_unwrap_control.tex"),
    )
    args = ap.parse_args()

    root = _ROOT
    py = sys.executable
    out_base = root / "outputs" / str(args.tag)
    expanded_inputs = _expand_inputs(root, list(args.inputs))

    simple_per_surface = out_base / "per_surface.csv"
    if bool(args.skip_base_reuse):
        simple_per_surface = out_base / "unwrap_control" / "simple" / "per_surface.csv"

    if not simple_per_surface.exists() and not args.skip_benchmark:
        cmd = [
            py,
            str(root / "scripts" / "benchmark_sur_interferometry.py"),
            *expanded_inputs,
            "--outdir",
            str(simple_per_surface.parent),
            "--nx",
            str(int(args.nx)),
            "--ny",
            str(int(args.ny)),
            "--nreps",
            str(int(args.nreps)),
        ]
        if int(args.limit) > 0:
            cmd.extend(["--limit", str(int(args.limit))])
        _run(cmd)

    least_sq_dir = out_base / "unwrap_control" / "least_squares"
    least_sq_per_surface = least_sq_dir / "per_surface.csv"
    if not args.skip_benchmark:
        cmd = [
            py,
            str(root / "scripts" / "benchmark_sur_interferometry.py"),
            *expanded_inputs,
            "--outdir",
            str(least_sq_dir),
            "--nx",
            str(int(args.nx)),
            "--ny",
            str(int(args.ny)),
            "--nreps",
            str(int(args.nreps)),
            "--unwrap-method",
            "least_squares",
        ]
        if int(args.limit) > 0:
            cmd.extend(["--limit", str(int(args.limit))])
        _run(cmd)

    simple_summary = _summary_by_method(_collapse_surface_rows(_load_rows(simple_per_surface)))
    least_sq_summary = _summary_by_method(_collapse_surface_rows(_load_rows(least_sq_per_surface)))

    summary_csv = out_base / "unwrap_control" / "summary.csv"
    _write_summary_csv(summary_csv, simple_summary, least_sq_summary)
    _write_latex_table(root / args.out_table, label=args.label, simple=simple_summary, least_squares=least_sq_summary)
    print(f"Wrote: {summary_csv}")
    print(f"Wrote: {root / args.out_table}")


if __name__ == "__main__":
    main()